<?php

if( function_exists('acf_add_local_field_group') ):

$settings = array (
	'key' => 'group_5bedfa77d2977',
	'title' => 'Project Settings',
	'fields' => array (
		array (
			'key' => 'field_5bedfa77d7bf2',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bedfa77d8dd0',
			'label' => 'Category Page Option',
			'name' => 'pjgs_category_page_options',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee756e5cfd0',
					'label' => 'Category Page',
					'name' => 'is_cat_page_enabled',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Enable',
					'ui_off_text' => 'Disable',
				),

			),
		),
		array (
			'key' => 'field_5bedfa77d7bf1',
			'label' => 'Buttons & Shortcuts',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bedfa77d8dde',
			'label' => 'Action Button - Listing Button',
			'name' => 'pjgs_action_btn_main',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee756e5cfde',
					'label' => 'Main Button Label',
					'name' => 'label',
					'type' => 'text',
					'value' => NULL,
					'instructions' => 'Default : Read more',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

			),
		),
		array (
			'key' => 'field_5bedfa77d7ccd',
			'label' => 'Action Button - Enquire',
			'name' => 'pjgs_action_btn_enquire',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee7c5c8c1a1',
					'label' => 'Visibility',
					'name' => 'visibility',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Show',
					'ui_off_text' => 'Hide',
				),
				array (
					'key' => 'field_5bee7d138c1a2',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee7c5c8c1a1',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5bee7d2e8c1a3',
					'label' => 'Show icon',
					'name' => 'show_icon',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee7c5c8c1a1',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_5bee7d588c1a4',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee7d2e8c1a3',
								'operator' => '==',
								'value' => '1',
							),
							array (
								'field' => 'field_5bee7c5c8c1a1',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => '',
					'show_preview' => '',
					'enqueue_fa' => '0',
					'fa_live_preview' => '',
					'choices' => array (
					),
				),
				array (
					'key' => 'field_5bee7d9e8c1a6',
					'label' => 'Button Target',
					'name' => 'button_target',
					'type' => 'button_group',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee7c5c8c1a1',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'link' => 'Link',
						'modal' => 'Modal',
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => '',
					'return_format' => '',
				),
				array (
					'key' => 'field_5bee7dc68c1a7',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee7d9e8c1a6',
								'operator' => '==',
								'value' => 'link',
							),
							array (
								'field' => 'field_5bee7c5c8c1a1',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => '',
				),
				array (
					'key' => 'field_5bee7ded8c1a9',
					'label' => 'Modal',
					'name' => 'data_open',
					'type' => 'select',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee7d9e8c1a6',
								'operator' => '==',
								'value' => 'modal',
							),
							array (
								'field' => 'field_5bee7c5c8c1a1',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_5bedfa77d7ef4',
			'label' => 'Single Page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bedfa77d7f62',
			'label' => 'Project Page Builder Elements',
			'name' => 'pjgs_page_builder_elements',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array (
				'5bc42d1b53136' => array (
					'key' => '5bc42d1b53136',
					'name' => 'description_&_gallery',
					'label' => 'Description & Gallery',
					'display' => 'block',
					'sub_fields' => array (
						array(
							'key' => 'field_5bc081119ae6e',
							'label' => 'Layout',
							'name' => 'cpts_desc_gallery_layout',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5bc0811233068',
									'label' => 'Select Display',
									'name' => 'display',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'image-above-content' => 'Gallery above content',
										'image-overlay-content' => 'Gallery overlay content centered',
										'image-left-content split-40-60' => 'Gallery left of content (40% | 60%)',
										'image-left-content split-50-50' => 'Gallery left of content (50% | 50%)',
										'image-right-content split-60-40' => 'Gallery right of content (60% | 40%)',
										'image-right-content split-50-50' => 'Gallery right of content (50% | 50%)',
										'image-right-content split-40-60' => 'Gallery right of content (40% | 60%)',
									),
									'default_value' => array(
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
							),
						),
						array(
							'key' => 'field_5bc27e4827938',
							'label' => 'Gallery',
							'name' => 'cpts_desc_gallery_settings',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array (
									'key' => 'field_5b84e8e75ef37',
									'label' => 'Gallery Type',
									'name' => 'gallery_type',
									'type' => 'button_group',
									'value' => NULL,
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'grid' => 'Grid',
										'slider' => 'Slider',
									),
									'allow_null' => 0,
									'default_value' => 'grid',
									'layout' => 'horizontal',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5bc101a786474',
									'label' => 'Gallery Thumbnails',
									'name' => 'thumbnails',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_5b84e8e75ef37',
												'operator' => '==',
												'value' => 'slider',
											),
										),
									),
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'message' => 'Display thumbnail images below gallery',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => 'Show',
									'ui_off_text' => 'Hide',
								),
								array (
									'key' => 'field_5bee78c74bedb',
									'label' => 'Per Row',
									'name' => 'per_row',
									'type' => 'select',
									'value' => NULL,
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_5b84e8e75ef37',
												'operator' => '==',
												'value' => 'grid',
											),
										),
									),
									'wrapper' => array (
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'medium-12' => '1 per row',
										'medium-6' => '2 per row',
										'medium-6 large-4' => '3 per row',
										'medium-6 large-3' => '4 per row',
									),
									'default_value' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5bc081119afca',
									'label' => 'Lightbox',
									'name' => 'lightbox',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'message' => 'Enable lightbox to display gallery images in popup',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
							),
						),
						array(
							'key' => 'field_7bc081119b0af',
							'label' => 'Design',
							'name' => 'cpts_desc_gallery_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bac772faef77',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc42eeb8b247' => array (
					'key' => '5bc42eeb8b247',
					'name' => 'tabbed_content',
					'label' => 'Tabbed Content',
					'display' => 'block',
					'sub_fields' => array (
						array(
							'key' => 'field_5bc081119b19e',
							'label' => 'Layout',
							'name' => 'cpts_tabs_layout',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'horizontal-tabs' => 'Tabs on Top',
								'vertical-tabs' => 'Tabs on Left',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5bc081119b216',
							'label' => 'Header',
							'name' => 'cpts_tabs_header',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5b90d65472f05',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc081119b36b',
							'label' => 'Design',
							'name' => 'cpts_tabs_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bac772faef77',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc42f368b249' => array (
					'key' => '5bc42f368b249',
					'name' => 'features',
					'label' => 'Features',
					'display' => 'block',
					'sub_fields' => array (
						array(
							'key' => 'field_5bc081119982f',
							'label' => 'Layout',
							'name' => 'cpts_features_layout',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5bc08111aa222',
									'label' => 'Select Layout',
									'name' => 'layout_type',
									'type' => 'button_group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'grid' => 'Grid',
										'carousel' => 'Carousel',
									),
									'allow_null' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5bc08111aa2a9',
									'label' => 'Select Display',
									'name' => 'display',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'content-only' => 'Content Only',
										'image-above-content' => 'Image above content',
										'image-overlay-content' => 'Image overlay content',
										'image-left-content split-25-75' => 'Image left of content (25% | 75%)',
										'image-left-content split-40-60' => 'Image left of content (40% | 60%)',
										'image-left-content split-50-50' => 'Image left of content (50% | 50%)',
										'image-right-content split-25-75' => 'Image right of content (75% | 25%)',
										'image-right-content split-60-40' => 'Image right of content (60% | 40%)',
										'image-right-content split-50-50' => 'Image right of content (50% | 50%)',
										'image-right-content split-40-60' => 'Image right of content (46% | 60%)',
										'image-left-content then-right split-50-50' => 'Image alternating left then right of content',
										'image-right-content then-left split-50-50' => 'Image alternating right then left of content',
										'icon-above-content' => 'Icon above content',
										'icon-left-content' => 'Icon left of content',
									),
									'default_value' => array(
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5bc08111aa327',
									'label' => 'Features per row',
									'name' => 'per_row',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'medium-12' => '1 per row',
										'medium-6' => '2 per row',
										'medium-4' => '3 per row',
										'medium-6 large-3' => '4 per row',
									),
									'default_value' => array(
										0 => 'medium-4',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
							),
						),
						array(
							'key' => 'field_5bc08111998af',
							'label' => 'Header',
							'name' => 'cpts_features_header',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5b90d65472f05',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc0811199a20',
							'label' => 'Design',
							'name' => 'cpts_features_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bac772faef77',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc431288948f' => array (
					'key' => '5bc431288948f',
					'name' => 'related',
					'label' => 'Related',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5bedfa77f082f',
							'label' => 'Related Layout',
							'name' => 'related_layout',
							'type' => 'clone',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array (
								0 => 'field_5c5a7900d68c6',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc081119a8fe',
							'label' => 'Header',
							'name' => 'cpts_related_header',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5b90d65472f05',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array (
							'key' => 'field_5bedfa77f082e',
							'label' => 'Related Design',
							'name' => 'related_design',
							'type' => 'clone',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array (
								0 => 'field_5b8e79de0c3a1',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc4318889491' => array (
					'key' => '5bc4318889491',
					'name' => 'videos',
					'label' => 'Video',
					'display' => 'block',
					'sub_fields' => array (
						array(
							'key' => 'field_5bc081119ac2e',
							'label' => 'Header',
							'name' => 'cpts_video_header',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5b90d65472f05',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc081119ad8c',
							'label' => 'Design',
							'name' => 'cpts_video_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bac772faef77',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc4321189493' => array (
					'key' => '5bc4321189493',
					'name' => 'faq',
					'label' => 'FAQ',
					'display' => 'block',
					'sub_fields' => array (
						array(
							'key' => 'field_5bc081119b622',
							'label' => 'Header',
							'name' => 'cpts_faq_header',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5b90d65472f05',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc081119b71c',
							'label' => 'Design',
							'name' => 'cpts_faq_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bac772faef77',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc4329b89496' => array (
					'key' => '5bc4329b89496',
					'name' => 'testimonials',
					'label' => 'Testimonials',
					'display' => 'block',
					'sub_fields' => array (
						array(
							'key' => 'field_5bc081119a39c',
							'label' => 'Layout',
							'name' => 'cpts_testimonials_layout',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5bc08111e19c2',
									'label' => 'Select Layout',
									'name' => 'layout_type',
									'type' => 'button_group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'grid' => 'Grid',
										'carousel' => 'Carousel',
									),
									'allow_null' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5bc08111e1a30',
									'label' => 'Select Display',
									'name' => 'testimonials_boxes_display',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'content-only' => 'Content Only',
										'image-above-content' => 'Image above content',
										'image-overlay-content' => 'Image overlay content',
										'image-left-content split-25-75' => 'Image left of content (25% | 75%)',
										'image-left-content split-40-60' => 'Image left of content (40% | 60%)',
										'image-left-content split-50-50' => 'Image left of content (50% | 50%)',
										'image-right-content split-25-75' => 'Image right of content (75% | 25%)',
										'image-right-content split-60-40' => 'Image right of content (60% | 40%)',
										'image-right-content split-50-50' => 'Image right of content (50% | 50%)',
										'image-right-content split-40-60' => 'Image right of content (60% | 40%)',
										'image-left-content then-right split-50-50' => 'Image alternating left then right of content',
										'image-right-content then-left split-50-50' => 'Image alternating right then left of content',
										'icon-above-content' => 'Icon above content',
										'icon-left-content' => 'Icon left of content',
									),
									'default_value' => array(
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5bc08111e1abe',
									'label' => 'Testimonials per row',
									'name' => 'per_row',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'medium-12' => '1 per row',
										'medium-6' => '2 per row',
										'medium-6 large-4' => '3 per row',
										'medium-6 large-3' => '4 per row',
									),
									'default_value' => array(
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
							),
						),
						array(
							'key' => 'field_5bc081119a416',
							'label' => 'Header',
							'name' => 'cpts_testimonials_header',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5b90d65472f05',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc081119a59a',
							'label' => 'Design',
							'name' => 'cpts_testimonials_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bac772faef77',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc4334989498' => array (
					'key' => '5bc4334989498',
					'name' => 'call_to_action',
					'label' => 'Call to Action',
					'display' => 'block',
					'sub_fields' => array (
						array(
							'key' => 'field_5bc0811199e66',
							'label' => 'Layout',
							'name' => 'cpts_cta_layout',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5bc08111cd0c5',
									'label' => 'Select Display',
									'name' => 'display',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'default-cta-layout' => 'Default Layout',
										'cta-layout-1' => 'One Column Centered',
										'cta-layout-2' => 'Content on Right',
										'cta-layout-3' => 'Content on Left',
									),
									'default_value' => array(
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
							),
						),
						array(
							'key' => 'field_5bc0811199ee7',
							'label' => 'Header',
							'name' => 'cpts_cta_header',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b90d6e2e75ed',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc0811199fdf',
							'label' => 'Design',
							'name' => 'cpts_cta_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bac772faef77',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc433d38949a' => array (
					'key' => '5bc433d38949a',
					'name' => 'global_element',
					'label' => 'Global Element',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5bedfa77f0a5d',
							'label' => 'Global Element',
							'name' => 'global_element',
							'type' => 'clone',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array (
								0 => 'field_5bc081119b803',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
		),
		array (
			'key' => 'field_5cbe157a6bd7e',
			'label' => 'Category Page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5bee756e5cfd0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d1c0238414e5',
			'label' => 'Banner Options',
			'name' => 'pct_banner_option',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array(
					'key' => 'field_48bd1a908d881',
					'label' => 'Banner Display',
					'name' => 'show_page_banner',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						"id" => ''
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Show',
					'ui_off_text' => 'Hide',
				),
				array (
					'key' => 'field_67ad1a908e072',
					'label' => 'Default Banner Image',
					'name' => 'cp_page_banner',
					'type' => 'image',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_48bd1a908d881',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5b3da9d237bf8',
					'label' => 'Banner height',
					'name' => 'page_banner_height',
					'type' => 'button_group',
					'instructions' => 'Select height of banner',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_48bd1a908d881',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'default-height' => 'Default',
						'short-banner' => 'Short',
						'tall-banner' => 'Tall',
                		'full-screen-banner' => 'Full Screen'
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					"key" => "field_5b3da9d237bf9",
					"label" => "Text Alignment",
					"name" => "page_banner_text_alignment",
					"type" => "button_group",
					"instructions" => "Select text alignment",
					"required" => 0,
					"conditional_logic" => array(
						array(
							array(
								"field" => "field_48bd1a908d881",
								"operator" => "==",
								"value" => "1"
							)
						)
					),
					"wrapper" => array(
						"width" => "33.33",
						"class" => "",
						"id" => ""
					),
					"choices" => array(
						"default-alignment" => "Default",
						"text-left" => "Left",
						"text-center" => "Center",
						"text-right" => "Right"
					),
					"allow_null" => 0,
					"default_value" => "",
					"layout" => "horizontal",
					"return_format" => "value"
				),
				array(
					"key" => "field_5b3da9d237bfa",
					"label" => "Background Filter",
					"name" => "background_overlay",
					"type" => "extended-color-picker",
					"instructions" => "Add a filter over the image to make text stand out",
					"required" => 0,
					"conditional_logic" => array(
						array(
							array(
								"field" => "field_48bd1a908d881",
								"operator" => "==",
								"value" => "1"
							)
						)
					),
					"wrapper" => array(
						"width" => "33.33",
						"class" => "",
						"id" => ""
					),
					"default_value" => "rgba(10,0,0,0.5)",
					"color_palette" => "rgba(10,0,0,0.5)",
					"hide_palette" => 0
				),
			),
		),

		array (
			'key' => 'field_6cd6265fc9e44',
			'label' => 'Page Element Builder',
			'name' => 'project_cat_element_builder',
			'type' => 'flexible_content',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array (
				'4bc42d1b5316' => array (
					'key' => '4bc42d1b5316',
					'name' => 'description',
					'label' => 'Description',
					'display' => 'block',
					'sub_fields' => array (

						array (
							'key' => 'field_5bc42d0b1a5ex',
							'label' => 'Descriptions',
							'name' => 'description',
							'type' => 'clone',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array (
								0 => 'field_5b8e79de0c3a1',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc4312889492' => array (
					'key' => '5bc4312889492',
					'name' => 'project',
					'label' => 'Project Listing',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5bc4312889491',
							'label' => 'Product List',
							'name' => 'product_list',
							'type' => 'clone',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array (
								0 => 'field_5c5a7900d68c6',
								1 => 'field_5c5a7924d68ca',
							),
							'display' => 'seamless',
							'layout' => '',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array (
							'key' => 'field_5bc4312889493',
							'label' => 'Listing Content Option',
							'name' => 'cpts_project_list_option',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_5bc4312889494',
									'label' => 'Featured',
									'name' => 'featured_projects',
									'type' => 'true_false',
									'instructions' => 'Display Featured Project',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array (
									'key' => 'field_5bc4312889495',
									'label' => 'Content to Display',
									'name' => 'project_content_to_display',
									'type' => 'checkbox',
									'value' => NULL,
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										"description" => "Description",
										"button" => "Button"
									),
									'allow_custom' => 0,
									'save_custom' => 0,
									'default_value' => ['description', 'button'],
									'layout' => 'vertical',
									'toggle' => 0,
									'return_format' => 'value'
								),						
							),
						),
						array (
							'key' => 'field_5bc4312889492',
							'label' => 'Project List Design',
							'name' => 'product_list_design',
							'type' => 'clone',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array (
								2 => 'field_5b8e79de0c3a1',
							),
							'display' => 'seamless',
							'layout' => '',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bc433d38930b' => array (
					'key' => '5bc433d38930b',
					'name' => 'global_element',
					'label' => 'Global Element',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5bc433d38941c',
							'label' => 'Call to Action',
							'name' => 'call_to_action',
							'type' => 'clone',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array (
								0 => 'field_5bac2c795ee2e',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
		),
	
	

	),
		
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-project-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
);

acf_add_local_field_group($settings);

endif;