<?php

if( function_exists('acf_add_local_field_group') ):

$options = array (
	'key' => 'group_5bee1ebca2301',
	'title' => 'Project Options',
	'fields' => array (
		array (
			'key' => 'field_5bee1ebca7ac0',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bee1ebca7c16',
			'label' => 'Actions',
			'name' => 'proj_actions_main',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee74834bec7',
					'label' => 'Enquire',
					'name' => 'enquire',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Show',
					'ui_off_text' => 'Hide',
				),
			),
		),
		array (
			'key' => 'field_5bee1ebca7cfc',
			'label' => 'Media',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bee1ebca7de0',
			'label' => 'Gallery',
			'name' => 'proj_images',
			'type' => 'gallery',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5bee1ebca7ec0',
			'label' => 'Project Tabs',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bee1ebca7f2e',
			'label' => 'Tabs',
			'name' => 'proj_tabbed_content',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Tab',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee1ebcb867c',
					'label' => 'Tab Title',
					'name' => 'title',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5bee1ebcb86f4',
					'label' => 'Tab Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_5bee1ebca7f9d',
			'label' => 'Project Features',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bee1ebca800b',
			'label' => 'Heading',
			'name' => 'proj_other_heading',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bee1ebca8078',
			'label' => 'Sub Heading Text',
			'name' => 'proj_other_desc',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_5bee1ebca80e6',
			'label' => 'Features',
			'name' => 'proj_other_project',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Feature',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee1ebcc3194',
					'label' => 'Label',
					'name' => 'name',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5bee1ebcc3217',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array (
					'key' => 'field_5bee1ebcc3290',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'font-awesome',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array (
					),
				),
				array (
					'key' => 'field_5bee1ebcc3308',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_5bee1ebca830c',
			'label' => 'Video',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_6bee1ebca947x',
			'label' => 'Display',
			'name' => 'hide_section',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Enabled',
			'ui_off_text' => 'Disabled',
		),
		array (
			'key' => 'field_5b7a4be20a76c',
			'label' => 'Video',
			'name' => 'prj_video',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_6bee1ebca947x',
						'operator' => '==',
						'value' => 1,
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5b84e8e75ef36',
					'label' => 'Video Source Type',
					'name' => 'video_source_type',
					'type' => 'button_group',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'embed' => 'Embed',
						'file' => 'File',
						'url' => 'URL',
					),
					'allow_null' => 0,
					'default_value' => 'embed',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_5b7a4c030a76d',
					'label' => 'Video Image placeholder',
					'name' => 'video_image_placeholder',
					'type' => 'image',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5b84e8e75ef36',
								'operator' => '!=',
								'value' => 'embed',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5b7a4c090a76e',
					'label' => 'Youtube Video URL',
					'name' => 'youtube_video',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5b84e8e75ef36',
								'operator' => '==',
								'value' => 'url',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5b79353b13dd4',
					'label' => 'Embed Code',
					'name' => 'embed_code',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => 'Paste the embed code here',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5b84e8e75ef36',
								'operator' => '==',
								'value' => 'embed',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_5d1adef15ea16',
					'label' => 'Video File',
					'name' => 'video_file',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5b84e8e75ef36',
								'operator' => '==',
								'value' => 'file',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_5b79343caf2b4',
			'label' => 'Details',
			'name' => 'video_details',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_6bee1ebca947x',
						'operator' => '==',
						'value' => 1,
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee75d04becc',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array (
					'key' => 'field_5bee75f24becd',
					'label' => 'Image Uploads',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => 'hidden',
						'id' => '',
					),
					'message' => 'Add different versions of Image for better screen size displays',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array (
					'key' => 'field_5bee76144bece',
					'label' => 'Desktop Version',
					'name' => 'desktop_version',
					'type' => 'image',
					'value' => NULL,
					'instructions' => 'Desktop version will be the default image for different screen size',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => 'hidden',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5bee76584becf',
					'label' => 'Tablet Version',
					'name' => 'tablet_version',
					'type' => 'image',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => 'hidden',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5bee767e4bed0',
					'label' => 'Mobile Version',
					'name' => 'mobile_version',
					'type' => 'image',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => 'hidden',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_5bee1ebca83e9',
			'label' => 'Related Projects',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		
		array (
			'key' => 'field_6cfd4ebca9568',
			'label' => 'Display',
			'name' => 'proj_related_display',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Enabled',
			'ui_off_text' => 'Disabled',
		),
		array (
			'key' => 'field_5bee1ebca8457',
			'label' => 'Heading Text',
			'name' => 'proj_related_heading',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
						array (
							array (
								'field' => 'field_6cfd4ebca9568',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bee1ebca84c4',
			'label' => 'Sub Heading Text',
			'name' => 'proj_related_desc',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
				'conditional_logic' => array (
						array (
							array (
								'field' => 'field_6cfd4ebca9568',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_5bee1ebca8532',
			'label' => 'Select Projects',
			'name' => 'proj_related_projects',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
				'conditional_logic' => array (
						array (
							array (
								'field' => 'field_6cfd4ebca9568',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Projects',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee1ebce79dc',
					'label' => 'Select Projects',
					'name' => 'select_project',
					'type' => 'post_object',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'project',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
			),
		),
		array (
			'key' => 'field_5bee1ebca85a0',
			'label' => 'FAQs',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bee1ebca860e',
			'label' => 'Heading Text',
			'name' => 'proj_faq_heading',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bee1ebca867c',
			'label' => 'Sub Heading Text',
			'name' => 'proj_faq_desc',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_5bee1ebca86eb',
			'label' => 'Content',
			'name' => 'proj_faq_contents',
			'type' => 'clone',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array (
				0 => 'field_5bb6b8c92cf0e',
				1 => 'field_5bada4c19cc66',
			),
			'display' => 'group',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 0,
		),
		array (
			'key' => 'field_5bee1ebca8759',
			'label' => 'Testimonials',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bee1ebca87c9',
			'label' => 'Heading Text',
			'name' => 'proj_reviews_heading',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bee1ebca8839',
			'label' => 'Sub Heading Text',
			'name' => 'proj_reviews_desc',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_5bee1ebca88a7',
			'label' => 'Contents',
			'name' => 'proj_reviews_contents',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee76e14bed1',
					'label' => 'Select Content',
					'name' => 'review_option_type',
					'type' => 'button_group',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Select' => 'Select',
						'Category' => 'Category',
						'Script' => 'Script',
					),
					'allow_null' => 0,
					'default_value' => 'Select',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_39372select_testimonial',
					'label' => 'Select Testimonial',
					'name' => 'testimonial_posts_id',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee76e14bed1',
								'operator' => '==',
								'value' => 'Select',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'testimonials_type',
					),
					'taxonomy' => '',
					'allow_null' => 1,
					'multiple' => 1,
					'return_format' => 'id',
					'ui' => 1,
				),
				array (
					'key' => 'field_5bee77054bed2',
					'label' => 'Script',
					'name' => 'script',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => 'Use embed script',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee76e14bed1',
								'operator' => '==',
								'value' => 'Script',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array (
					'key' => 'field_5bf2e6170560c',
					'label' => 'Content',
					'name' => 'testimonials_list',
					'type' => 'clone',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee76e14bed1',
								'operator' => '==',
								'value' => 'Category',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'clone' => array (						
						1 => 'field_5bbac2d974bcf',
						2 => 'field_5bacd8a928742',
						3 => 'field_5bacd8df28743',
					),
					'display' => 'group',
					'layout' => 'block',
					'prefix_label' => 0,
					'prefix_name' => 0,
				),
			),
		),
		array (
			'key' => 'field_5bee1ebca8915',
			'label' => 'Call to Action',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bee1ebca8983',
			'label' => 'Content',
			'name' => 'proj_section',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5bee77404bed3',
					'label' => 'Display',
					'name' => 'hide_section',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Enabled',
					'ui_off_text' => 'Disabled',
				),
				array (
					'key' => 'field_1cfe756e4brdc',
					'label' => 'Heading Text',
					'name' => 'heading_text',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee77404bed3',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5bee775b4bed4',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee77404bed3',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array (
					'key' => 'field_5bee77fa4bed5',
					'label' => 'Group Button',
					'name' => 'call_to_action_button',
					'type' => 'repeater',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5bee77404bed3',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_5bee781a4bed6',
							'label' => 'Button target',
							'name' => 'button_target',
							'type' => 'button_group',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33.33',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'link' => 'Link',
								'modal' => 'Modal',
							),
							'allow_null' => 0,
							'default_value' => 'link',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_5bee78544bed7',
							'label' => 'Link',
							'name' => 'link',
							'type' => 'link',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5bee781a4bed6',
										'operator' => '==',
										'value' => 'link',
									),
								),
							),
							'wrapper' => array (
								'width' => '66.66',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array (
							'key' => 'field_5bee787e4bed8',
							'label' => 'Modal',
							'name' => 'modal',
							'type' => 'group',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5bee781a4bed6',
										'operator' => '==',
										'value' => 'modal',
									),
								),
							),
							'wrapper' => array (
								'width' => '66.66',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_5bee78944bed9',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'value' => NULL,
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5bee78c74beda',
									'label' => 'Select Modal',
									'name' => 'data_open',
									'type' => 'select',
									'value' => NULL,
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
									),
									'default_value' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'return_format' => 'value',
									'placeholder' => '',
								),
							),
						),
					),
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'project',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	//	0 => 'excerpt',
		0 => 'discussion',
		1 => 'comments',
		2 => 'author',
	//	4 => 'featured_image',
	),
	'active' => 1,
	'description' => '',
);

// Update Action fields
// $fields_visibility_settings = array(
// 	['field' => 'field_5bee1ebca7c16', // Actions @ General 
// 		'sub_fields' => [
// 			['key' => 'field_5bee74834bec7', // Enquire
// 				'visible'=> _get_field_value('pjgs_action_btn_enquire', 'options')['visibility'] ]
// 		]
// 	]
// );

// foreach ($fields_visibility_settings as $field_vs) {
// 	$position = array_search($field_vs['field'], array_column($options['fields'], 'key'));
// 	if(isset($field_vs['sub_field'])){
// 		$position2 = array_search($field_vs['sub_field'], array_column($options['fields'][$position]['sub_fields'], 'key'));
// 		foreach ($field_vs['sub_fields'] as $sub) {
// 			if(!$sub['visible']) {
// 				$position3 = array_search($sub['key'], array_column($options['fields'][$position]['sub_fields'][$position2]['sub_fields'], 'key'));
// 				array_splice($options['fields'][$position]['sub_fields'][$position2]['sub_fields'], $position3, 1);
// 			}
// 		}
// 	} else {
// 		foreach ($field_vs['sub_fields'] as $sub) {
// 			if(!$sub['visible']) {
// 				$position2 = array_search($sub['key'], array_column($options['fields'][$position]['sub_fields'], 'key'));
// 				array_splice($options['fields'][$position]['sub_fields'], $position2, 1);
// 			}
// 		}
// 	}
// }

acf_add_local_field_group($options);

endif;