<?php
if( function_exists('acf_add_local_field_group') ):

	$property_display_title = get_field('op_display_title', 'options');
    $property_ctd_opt = array(
		'categories' => 'Categories',
        'headline' => 'Headline',
        'suburb' => 'Suburb',                    
        'address' => 'Address',
        'description' => "Text",
        'price' => 'Price',
        'meta' => 'Meta Details',
        'button' => 'Button',
    );

    if($property_display_title == 'headline'){
        array_splice($property_ctd_opt, 0, 1);
    }

    if($property_display_title == 'suburb'){
        array_splice($property_ctd_opt, 1, 1);
	}

	$post_type_choices = array();

	if(is_element_exists('courses')) $post_type_choices['courses'] = 'Courses';
	if(is_element_exists('designs')) $post_type_choices['designs'] = 'Design';
	if(is_element_exists('events')) $post_type_choices['events'] = 'Events';
	if(is_element_exists('gallery')) $post_type_choices['gallery'] = 'Gallery';
	if(is_element_exists('listing_section')) {
		$post_type_choices['auction'] = 'Auction';
		$post_type_choices['listings'] = 'Listings';
		$post_type_choices['inspections'] = 'Inspections';
	}
	if(is_element_exists('location')) $post_type_choices['locations'] = 'Locations';
	if(is_element_exists('recent_posts')) $post_type_choices['posts'] = 'Posts';
	if(is_element_exists('products')) $post_type_choices['products'] = 'Products';
	if(is_element_exists('projects')) $post_type_choices['projects'] = 'Projects';
	if(is_element_exists('testimonials')) $post_type_choices['testimonials'] = 'Reviews';
	
	
	
acf_add_local_field_group(array(
	'key' => 'group_5ae04692aaa12',
	'title' => 'CPT Options',
	'fields' => array(
		array(
			'key' => 'field_5bb7dc4b949c3',
			'label' => 'Layout',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		 array(
            'key' => 'field_5b71363bb3321',
            'label' => 'Grid Layout',
            'name' => 'cpt_grid_layout',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'default-grid-layout' => 'Default Layout',
                'grid-layout-1' => 'Grid Layout 1',
                'grid-layout-2' => 'Grid Layout 2',
                'grid-layout-3' => 'Grid Layout 3',
            ),
            'default_value' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
		array(
			'key' => 'field_5bb7dc633e2ab',
			'label' => 'Select Display',
			'name' => 'display',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'content-only' => 'Content Only',
				'image-above-content' => 'Image above content',
				'image-overlay-content' => 'Image overlay content',
				'image-left-content split-25-75' => 'Image left of content (25% | 75%)',
				'image-left-content split-40-60' => 'Image left of content (40% | 60%)',
				'image-left-content split-50-50' => 'Image left of content (50% | 50%)',
				'image-right-content split-25-75' => 'Image right of content (75% | 25%)',
				'image-right-content split-40-60' => 'Image right of content (60% | 40%)',
				'image-right-content split-50-50' => 'Image right of content (50% | 50%)',
				'image-left-content then-right split-50-50' => 'Image alternating left then right of content',
				'image-right-content then-left split-50-50' => 'Image alternating right then left of content',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bb7dca93e2ac',
			'label' => 'Per Row',
			'name' => 'per_row',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'medium-12' => '1 per row',
				'medium-6' => '2 per row',
				'medium-6 large-4' => '3 per row',
				'medium-6 large-3' => '4 per row',
			),
			'default_value' => array(
				0 => 'medium-6 large-4',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b000a65eb59b',
			'label' => 'Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		 array(
                'key' => 'field_5bb42ac14333c',
                'label' => 'Header',
                'name' => 'cpt_content_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5b90d65472f05',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
		array(
			'key' => 'field_5bb6df694b775',
			'label' => 'Post Type',
			'name' => 'post_type',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'cpt-post-type',
				'id' => '',
			),
			'choices' => $post_type_choices,
			'allow_null' => 1,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5bb7c439713f5',
			'label' => 'Categories',
			'name' => 'posts_categories',
			'type' => 'taxonomy',
			'instructions' => 'Leave blank to display all',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'posts',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'checkbox',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
		 array(
            'key' => 'field_5c5a79413s3s3',
            'label' => 'Listing to Display',
            'name' => 'cpt_events_listing_display',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'events',
					),
				),
			),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'recent' => 'Upcoming',
                'past' => 'Passed',
            ),
            'allow_null' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
		array(
			'key' => 'field_5db7c439714df',
			'label' => 'Categories',
			'name' => 'events_categories',
			'type' => 'taxonomy',
			'instructions' => 'Leave blank to display all',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'events',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'events_cat',
			'field_type' => 'checkbox',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array (
                        'key' => 'field_5bc4312183131',
                        'label' => 'Content to Display',
                        'name' => 'cpt_event_content_to_display',
                        'type' => 'checkbox',
                        'value' => NULL,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'events',
					),
				),
			),
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array (
                            "description" => "Text",                            
                            "category" => "Category",
                            "date_time" => "Event Date and Times",
                            "button" => "Button"
                        ),
                        'allow_custom' => 0,
                        'save_custom' => 0,
                        'default_value' => ['date_time', 'description', 'button'],
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value'
                    ),
                    array(
                        'key' => 'field_5c513941138cf',
                        'label' => 'Text to display',
                        'name' => 'cpt_event_text_to_display',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bc4312183131',
                                    'operator' => '==',
                                    'value' => 'description',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'excerpt' => 'Excerpt',
                            'description' => 'Description',
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
            array(
                'key' => 'field_5c5a794432131',
                'label' => 'Max number of words',
                'name' => 'cpt_event_max_number_of_words',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bc4312183131',
                            'operator' => '==',
                            'value' => 'description',
                        ),
                        array(
                            'field' => 'field_5c513941138cf',
                            'operator' => '==',
                            'value' => 'description',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 20,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 15,
                'max' => 50,
                'step' => '',
            ),
            
        array(
                'key' => 'field_5bb3c22111131',
                'label' => 'Group by Category',
                'name' => 'cpt_gallery_categorized_items',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                  'conditional_logic' => array(
    				array(
    					array(
    						'field' => 'field_5bb6df694b775',
    						'operator' => '==',
    						'value' => 'gallery',
    					),
    				),
    			),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        	array(
                'key' => 'field_5bb3c22333133',
                'label' => 'Group by Category',
                'name' => 'cpt_group_by_category',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                  'conditional_logic' => array(
    				array(
    					array(
    						'field' => 'field_5bb6df694b775',
    						'operator' => '!=',
    						'value' => 'gallery',
    					),
    				),
    			),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5ca324c193132',
                'label' => 'Categories',
                'name' => 'cpt_gallery_categories',
                'type' => 'taxonomy',
                'instructions' => 'Select categories to display or leave blank to show all',
                'required' => 0,
                 'conditional_logic' => array(
    				array(
    					array(
    						'field' => 'field_5bb6df694b775',
    						'operator' => '==',
    						'value' => 'gallery',
    					),
    				),
    			),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'gallery_cat',
                'field_type' => 'checkbox',
                'add_term' => 0,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'object',
                'multiple' => 0,
                'allow_null' => 0,
            ),
		array(
			'key' => 'field_5c652cc336856',
			'label' => 'Post Meta Options',
			'name' => 'post_meta_options',
			'type' => 'checkbox',
			'instructions' => 'Check post meta data to display on the page',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'posts',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'date' => 'Date',
				'author' => 'Author',
				'category' => 'Category',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5bb6e068c9df0',
			'label' => 'Categories',
			'name' => 'designs_categories',
			'type' => 'taxonomy',
			'instructions' => 'Leave blank to display all',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'designs',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'design_cat',
			'field_type' => 'checkbox',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_5af814f7fed45',
			'label' => 'Listing Image',
			'name' => 'designs_image_type',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'designs',
					),
				),
			
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'featured' => 'Featured',
				'slider' => 'Slider',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5af814f7fed43',
			'label' => 'Listing Image',
			'name' => 'properties_image_type',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'listings',
					),
				),
			
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'featured' => 'Featured',
				'slider' => 'Slider',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_cpt_le_e81b15d',
			'label' => 'Categories',
			'name' => 'listing_categories',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			 'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'listings',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'property_cat',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array(
			'key' => 'field_5b075426f4421',
			'label' => 'Listing Types',
			'name' => 'property_search_listing_types',
			'type' => 'radio',
			'instructions' => 'This determines which search form displays on the page',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'listings',
					),
				),
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'inspections',
					),
				),
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'auction',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'residential' => 'Residential',
				'commercial' => 'Commercial',
				'land' => 'Land',
				'business' => 'Business',
				'rural' => 'Rural',
				'all' => 'All',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5b000a80eb59c',
			'label' => 'Pricing Types',
			'name' => 'property_search_pricing_types',
			'type' => 'radio',
			'instructions' => 'Select property pricing types to display on this page.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'listings',
					),
				),
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'inspections',
					),
				),
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'auction',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'sale' => 'For Sale',
				'rent' => 'For Rent',
				'sold' => 'Sold',
				'leased' => 'Leased',
				'all' => 'All',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5bbc48f68109a',
			'label' => 'Tags',
			'name' => 'property_tags',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'listings',
					),
				),
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'inspections',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5bb6dfac4b776',
			'label' => 'Categories',
			'name' => 'services_categories',
			'type' => 'taxonomy',
			'instructions' => 'Leave blank to display all',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'services',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'services_cat',
			'field_type' => 'checkbox',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
                'key' => 'field_5bb6e068c2d13',
                'label' => 'Categories',
                'name' => 'locations_categories',
                'type' => 'taxonomy',
                'instructions' => 'Leave blank to display all',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bb6df694b775',
                            'operator' => '==',
                            'value' => 'locations',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'location_cat',
                'field_type' => 'checkbox',
                'add_term' => 1,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
            ),
            array(
                'key' => 'field_5bbc4871c1313',
                'label' => 'Content to display',
                'name' => 'locations_content_to_display',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bb6df694b775',
                            'operator' => '==',
                            'value' => 'locations',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                 'choices' => array (
                    "category" => "Category",
                    "contact" => "Contact Information",
                    "description" => "Text",                    
                    "button" => "Button"
                ),
                'allow_custom' => 0,
                'save_custom' => 0,
                'default_value' => array(
                    0 => 'description',
                ),
                'layout' => 'vertical',
                'toggle' => 0,
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5c5a7940d1313',
                'label' => 'Text to display',
                'name' => 'text_to_display',
                'type' => 'button_group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bbc4871c1313',
                            'operator' => '==',
                            'value' => 'description',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'excerpt' => 'Excerpt',
                    'description' => 'Description',
                ),
                'allow_null' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
			),
			array(
                'key' => 'field_cpt_le_1c1313',
                'label' => 'Content to display',
                'name' => 'property_content_to_display',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bb6df694b775',
                            'operator' => '==',
                            'value' => 'listings',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                 'choices' => $property_ctd_opt,
                'allow_custom' => 0,
                'save_custom' => 0,
                'default_value' => array(
                    0 => 'description',
                ),
                'layout' => 'vertical',
                'toggle' => 0,
                'return_format' => 'value',
            ),
             array(
                'key' => 'field_5d3fdddf23482',
                'label' => 'Display Main Content',
                'name' => 'cpt_display_main_conent',
                'type' => 'true_false',
                'instructions' => 'Display the Main Content above Listings',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5c5a794136135',
                'label' => 'Max number of words',
                'name' => 'max_number_of_words',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5c5a7940d68c4',
                            'operator' => '==',
                            'value' => 'description',
                        ),
                        array(
                            'field' => 'field_5bbc48787f3b2',
                            'operator' => '==',
                            'value' => 'description',
						),
					),
					array(
						array(
                            'field' => 'field_cpt_le_1c1313',
                            'operator' => '==',
                            'value' => 'description',
                        ),
					),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 20,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 15,
                'max' => 50,
                'step' => '',
            ),
		array(
                'key' => 'field_5bb6e068c9de9',
                'label' => 'Categories',
                'name' => 'products_categories',
                'type' => 'taxonomy',
                'instructions' => 'Leave blank to display all',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bb6df694b775',
                            'operator' => '==',
                            'value' => 'products',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'product_cat',
                'field_type' => 'checkbox',
                'add_term' => 1,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
            ),
            array(
                'key' => 'field_5bbc48787f3b2',
                'label' => 'Content to display',
                'name' => 'product_content_to_display',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bb6df694b775',
                            'operator' => '==',
                            'value' => 'products',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'category' => 'Category',
                    'description' => 'Text',
                    'price' => 'Price',
                    'button' => 'Button',
                ),
                'allow_custom' => 0,
                'save_custom' => 0,
                'default_value' => array(
                    0 => 'description',
                ),
                'layout' => 'vertical',
                'toggle' => 0,
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5c5a7940d68c4',
                'label' => 'Text to display',
                'name' => 'text_to_display',
                'type' => 'button_group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5bbc48787f3b2',
                            'operator' => '==',
                            'value' => 'description',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'excerpt' => 'Excerpt',
                    'description' => 'Description',
                ),
                'allow_null' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
		array(
			'key' => 'field_5c60ab5008fda',
			'label' => 'Categories',
			'name' => 'project_categories',
			'type' => 'taxonomy',
			'instructions' => 'Leave blank to display all',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'projects',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'project_cat',
			'field_type' => 'checkbox',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_5be12d6dafd60',
			'label' => 'Categories',
			'name' => 'testimonials_categories',
			'type' => 'taxonomy',
			'instructions' => 'Leave blank to display all',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'testimonials',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'testimonials_cat',
			'field_type' => 'checkbox',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_5adec52021752',
			'label' => 'Search Filter',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ae051f4d6579',
			'label' => 'Search Form',
			'name' => 'show_search_form',
			'type' => 'true_false',
			'instructions' => 'Show or Hide Search Filter Form on the page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
			'key' => 'field_5b075427f4432',
			'label' => 'Search Filter Layout',
			'name' => 'search_listing_layout',
			'type' => 'radio',
			'instructions' => 'This determines which search form displays on the page',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'designs',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'cpt-list-search-layout1' => 'Layout 1',
				'cpt-list-search-layout2' => 'Layout 2',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5ae051fed6581',
			'label' => 'Search Form Title',
			'name' => 'property_search_form_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Search',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ae051f4d6580',
			'label' => 'Show Search Filter',
			'name' => 'show_property_search_form',
			'type' => 'true_false',
			'instructions' => 'Allow users to filter post by entering search criteria. Not recommended for fewer listings.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
			'key' => 'field_5bc05baf9ed74',
			'label' => 'Search Filter Placeholder',
			'name' => 'search_filter_placeholder',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ae051f4d6580',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Search Properties',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63470c470f1',
			'label' => 'Show Category Filter',
			'name' => 'show_category_filter',
			'type' => 'true_false',
			'instructions' => 'Allow users to filter results by category.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'listings',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'designs',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
            'key' => 'field_5c833c81a2313',
            'label' => 'Category Filter Type',
            'name' => 'category_filter_type',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c63470c470f1',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'select' => 'Select',
                'checkbox' => 'Checkbox',  
                'list' => 'List',                        
            ),
            'allow_null' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        	array(
			'key' => 'field_5c634c6c470f5',
			'label' => 'Category Filter Placeholder',
			'name' => 'category_filter_placeholder',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c63470c470f1',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'listings',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'designs',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
						array(
						'field' => 'field_5c833c81a2313',
						'operator' => '==',
						'value' => 'select',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'All Category',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		
		array(
			'key' => 'field_5c63413s41rc2',
			'label' => 'Show Tag Filter',
			'name' => 'cpt_show_tag_filter',
			'type' => 'true_false',
			'instructions' => 'Allow users to filter results by tag.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'locations',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
			array(
			'key' => 'field_51634c6c32324',
			'label' => 'Tag Filter Placeholder',
			'name' => 'cpt_tag_filter_placeholder',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c63413s41rc2',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'All Tags',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		
		array(
			'key' => 'field_5c63414d52133',
			'label' => 'Show State Filter',
			'name' => 'cpt_show_state_filter',
			'type' => 'true_false',
			'instructions' => 'Allow users to filter results by state.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '==',
						'value' => 'locations',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
			array(
			'key' => 'field_5c63414d32333',
			'label' => 'State Filter Placeholder',
			'name' => 'cpt_state_filter_placeholder',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c63414d52133',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'All State',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c63476c470f2',
			'label' => 'Show Alphabetical Filter',
			'name' => 'show_alphabetical_filter',
			'type' => 'true_false',
			'instructions' => 'Allow users to sort results by title in ascending or descending order.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'listings',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'designs',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
			array(
			'key' => 'field_5c634cab470f6',
			'label' => 'Alphabetical Filter Placeholder',
			'name' => 'alphabetical_filter_placeholder',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c63476c470f2',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'listings',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'designs',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Order By',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c634850470f3',
			'label' => 'Show Date Filter',
			'name' => 'show_date_filter',
			'type' => 'true_false',
			'instructions' => 'Allow users to filter results by date.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'listings',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'designs',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
// 		array(
// 			'key' => 'field_5c634c6c470f5',
// 			'label' => 'Category Filter Placeholder',
// 			'name' => 'category_filter_placeholder',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => array(
// 				array(
// 					array(
// 						'field' => 'field_5c63470c470f1',
// 						'operator' => '==',
// 						'value' => '1',
// 					),
// 					array(
// 						'field' => 'field_5bb6df694b775',
// 						'operator' => '!=',
// 						'value' => 'listings',
// 					),
// 					array(
// 						'field' => 'field_5ae051f4d6579',
// 						'operator' => '==',
// 						'value' => '1',
// 					),
// 						array(
// 						'field' => 'field_5c833c81a2313',
// 						'operator' => '==',
// 						'value' => 'select',
// 					),
// 				),
// 			),
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => 'All Category',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 		),
// 		array(
// 			'key' => 'field_51634c6c32324',
// 			'label' => 'Tag Filter Placeholder',
// 			'name' => 'cpt_tag_filter_placeholder',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => array(
// 				array(
// 					array(
// 						'field' => 'field_5c63413s41rc2',
// 						'operator' => '==',
// 						'value' => '1',
// 					),
// 				),
// 			),
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => 'All Tags',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 		),
	
		array(
			'key' => 'field_5c634d1a470f7',
			'label' => 'Date Filter Placeholder',
			'name' => 'date_filter_placeholder',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c634850470f3',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'listings',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'designs',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'By Month',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c634850670f3',
			'label' => 'Show Clear Filter Option',
			'name' => 'show_clear_filter',
			'type' => 'true_false',
			'instructions' => 'Allow users to clear filter fields.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'listings',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'designs',
					),
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
			'key' => 'field_5c634d1a670f7',
			'label' => 'Clear Filter Label',
			'name' => 'clear_filter_label',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ae051f4d6579',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'listings',
					),
					array(
						'field' => 'field_5bb6df694b775',
						'operator' => '!=',
						'value' => 'designs',
					),
					array(
						'field' => 'field_5c634850670f3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Clear All',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bbf052221f4c',
			'label' => 'Results',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ad963aef1102',
			'label' => 'Number of Results to Display',
			'name' => 'op_property_to_show',
			'type' => 'number',
			'instructions' => 'Specify the number of listings to display per page. Default is set to 9 items.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '1',
			'max' => '',
			'step' => 1,
		),
		array(
			'key' => 'field_5c634ea46639e',
			'label' => 'Result Loading type',
			'name' => 'paging_type',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'pagination' => 'Pagination',
				'load_more' => 'Load More',
			),
			'allow_null' => 0,
			'default_value' => 'pagination',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5bbf3bc217275',
			'label' => 'No Search Results',
			'name' => 'no_search_results',
			'type' => 'wysiwyg',
			'instructions' => 'Please enter the text to be displayed if no search results are found.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Sorry, no search results found. Please try again.',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5bbe9a104ce27',
			'label' => 'Design',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bbe9a1e4ce28',
			'label' => 'Design',
			'name' => 'design',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'field_5bac44613133c',
				1 => 'field_5bac77600165c',
				2 => 'field_5bac77d80165d',
				3 => 'field_5bac782c0165f',
				4 => 'field_5bac783b01660',
			),
			'display' => 'seamless',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-cpt-archive.php',
			),
		),
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'woo_shop_page',
			)
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>