<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5bc0811187d40',
        'title' => 'CPT Page Builder Elements',
        'fields' => array(
            array(
                'key' => 'field_5bc0811199109',
                'label' => 'Page Sections',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc081119918b',
                'label' => 'Instructions',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Select which page element you would like to display on the page. A tab will display the page element to allow you to customise it.',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5bc081119920a',
                'label' => 'Elements',
                'name' => 'page_element_selection',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_5bc081119adfc',
                'label' => 'Description & Gallery',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc081119ae6d',
                'label' => 'Layout',
                'name' => 'cpts_desc_gallery_layout',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5bc0811233067',
                        'label' => 'Select Display',
                        'name' => 'display',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'image-above-content' => 'Gallery above content',
                            'image-overlay-content' => 'Gallery overlay content centered',
                            'image-left-content split-40-60' => 'Gallery left of content (40% | 60%)',
                            'image-left-content split-50-50' => 'Gallery left of content (50% | 50%)',
                            'image-right-content split-60-40' => 'Gallery right of content (60% | 40%)',
                            'image-right-content split-50-50' => 'Gallery right of content (50% | 50%)',
                            'image-right-content split-40-60' => 'Gallery right of content (40% | 60%)',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5bc27e4827937',
                'label' => 'Gallery',
                'name' => 'cpts_desc_gallery_settings',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5bc101a786473',
                        'label' => 'Gallery Thumbnails',
                        'name' => 'thumbnails',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => 'Display thumbnail images below gallery',
                        'default_value' => 1,
                        'ui' => 1,
                        'ui_on_text' => 'Show',
                        'ui_off_text' => 'Hide',
                    ),
                    array(
                        'key' => 'field_5adba313ccs3w31',
                        'label' => 'Auto Play',
                        'name' => 'slider_autoplay',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bc101a786473',
                                    'operator' => '==',
                                    'value' => 1,
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Enable',
                        'ui_off_text' => 'Disable',
                    ),
                    array(
                        'key' => 'field_5adb4323zx4d5',
                        'label' => 'Slider Speed',
                        'name' => 'slider_speed',
                        'type' => 'number',
                        'instructions' => 'Please select transition speed between gallery slides',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bc101a786473',
                                    'operator' => '==',
                                    'value' => 1,
                                ),
                                array(
                                    'field' => 'field_5adba313ccs3w31',
                                    'operator' => '==',
                                    'value' => 1,
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 6,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => 'seconds',
                        'min' => 1,
                        'max' => 20,
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_5bc081119afc9',
                        'label' => 'Lightbox',
                        'name' => 'lightbox',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => 'Enable lightbox to display gallery images in popup',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5bc081119b0ae',
                'label' => 'Design',
                'name' => 'cpts_desc_gallery_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119b11e',
                'label' => 'Tabbed Content',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc081119b19d',
                'label' => 'Layout',
                'name' => 'cpts_tabs_layout',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'horizontal-tabs' => 'Tabs on Top',
                    'vertical-tabs' => 'Tabs on Left',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5bc081119b215',
                'label' => 'Header',
                'name' => 'cpts_tabs_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5b90d65472f05',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119b36a',
                'label' => 'Design',
                'name' => 'cpts_tabs_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc08111997ac',
                'label' => 'Features',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc081119982e',
                'label' => 'Layout',
                'name' => 'cpts_features_layout',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5bc08111aa221',
                        'label' => 'Select Layout',
                        'name' => 'layout_type',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'grid' => 'Grid',
                            'carousel' => 'Carousel',
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'field_5b71354bbe251',
                        'label' => 'Grid Layout',
                        'name' => 'grid_layout',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bc08111aa221',
                                    'operator' => '==',
                                    'value' => 'grid',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'default-grid-layout' => 'Default Layout',
                            'grid-layout-1' => 'Grid Layout 1',
                            'grid-layout-2' => 'Grid Layout 2',
                            'grid-layout-3' => 'Grid Layout 3',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5bc08111aa2a8',
                        'label' => 'Select Display',
                        'name' => 'display',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'content-only' => 'Content Only',
                            'image-above-content' => 'Image above content',
                            'image-overlay-content' => 'Image overlay content',
                            'image-left-content split-25-75' => 'Image left of content (25% | 75%)',
                            'image-left-content split-40-60' => 'Image left of content (40% | 60%)',
                            'image-left-content split-50-50' => 'Image left of content (50% | 50%)',
                            'image-right-content split-25-75' => 'Image right of content (75% | 25%)',
                            'image-right-content split-60-40' => 'Image right of content (60% | 40%)',
                            'image-right-content split-50-50' => 'Image right of content (50% | 50%)',
                            'image-right-content split-40-60' => 'Image right of content (46% | 60%)',
                            'image-left-content then-right split-50-50' => 'Image alternating left then right of content',
                            'image-right-content then-left split-50-50' => 'Image alternating right then left of content',
                            'icon-above-content' => 'Icon above content',
                            'icon-left-content' => 'Icon left of content',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5bc08111aa326',
                        'label' => 'Boxes per row',
                        'name' => 'per_row',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'medium-12' => '1 per row',
                            'medium-6' => '2 per row',
                            'medium-4' => '3 per row',
                            'medium-6 large-3' => '4 per row',
                            'medium-4 large-2_4' => '5 per row',
                            'medium-4 large-2' => '6 per row',
                        ),
                        'default_value' => array(
                            0 => 'medium-4',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                     array(
                        'key' => 'field_5adba4119e2d4',
                        'label' => 'Auto Play',
                        'name' => 'slider_autoplay',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bc08111aa221',
                                    'operator' => '==',
                                    'value' => 'carousel',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Enable',
                        'ui_off_text' => 'Disable',
                    ),
                     array(
                        'key' => 'field_5b075b0d14d21',
                        'label' => 'Slider Speed',
                        'name' => 'slider_speed',
                        'type' => 'number',
                        'instructions' => 'Please select transition speed between slides',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5adba4119e2d4',
                                    'operator' => '==',
                                    'value' => 1,
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 6,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => 'seconds',
                        'min' => 1,
                        'max' => 20,
                        'step' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5bc08111998ae',
                'label' => 'Header',
                'name' => 'cpts_features_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5b90d65472f05',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc0811199a2f',
                'label' => 'Design',
                'name' => 'cpts_features_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc0811199ab0',
                'label' => 'Product Variations',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc0811199b38',
                'label' => 'Layout',
                'name' => 'cpts_variations_layout',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5bc08111bcf6c',
                        'label' => 'Select Layout',
                        'name' => 'layout_type',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'grid' => 'Grid',
                            'carousel' => 'Carousel',
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'field_5b71363aaf321',
                        'label' => 'Grid Layout',
                        'name' => 'grid_layout',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bc08111bcf6c',
                                    'operator' => '==',
                                    'value' => 'grid',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'default-grid-layout' => 'Default Layout',
                            'grid-layout-1' => 'Grid Layout 1',
                            'grid-layout-2' => 'Grid Layout 2',
                            'grid-layout-3' => 'Grid Layout 3',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5bc08111bd058',
                        'label' => 'Select Display',
                        'name' => 'display',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'image-above-content' => 'Image above content',
                            'image-overlay-content' => 'Image overlay content',
                            'image-left-content split-25-75' => 'Image left of content (25% | 75%)',
                            'image-left-content split-40-60' => 'Image left of content (40% | 60%)',
                            'image-left-content split-50-50' => 'Image left of content (50% | 50%)',
                            'image-right-content split-25-75' => 'Image right of content (75% | 25%)',
                            'image-right-content split-40-60' => 'Image right of content (60% | 40%)',
                            'image-right-content split-50-50' => 'Image right of content (50% | 50%)',
                            'image-left-content then-right split-50-50' => 'Image alternating left then right of content',
                            'image-right-content then-left split-50-50' => 'Image alternating right then left of content',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5bc08111bcfe6',
                        'label' => 'Per row',
                        'name' => 'per_row',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'medium-12' => '1 per row',
                            'medium-6' => '2 per row',
                            'medium-4' => '3 per row',
                            'medium-6 large-3' => '4 per row',
                        ),
                        'default_value' => array(
                            0 => 'medium-4',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_4ceca3229f113',
                        'label' => 'Auto Play',
                        'name' => 'slider_autoplay',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bc08111bcf6c',
                                    'operator' => '==',
                                    'value' => 'carousel',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Enable',
                        'ui_off_text' => 'Disable',
                    ),
                     array(
                        'key' => 'field_5d155b0c46r32',
                        'label' => 'Slider Speed',
                        'name' => 'slider_speed',
                        'type' => 'number',
                        'instructions' => 'Please select transition speed between slides',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_4ceca3229f113',
                                    'operator' => '==',
                                    'value' => 1,
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 6,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => 'seconds',
                        'min' => 1,
                        'max' => 20,
                        'step' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5bc0811199bbc',
                'label' => 'Header',
                'name' => 'cpts_variations_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5b90d65472f05',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc0811199d43',
                'label' => 'Design',
                'name' => 'cpts_variations_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119a80a',
                'label' => 'Related',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc081119a883',
                'label' => 'Layout',
                'name' => 'cpts_related_layout',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5bc0811214c2a',
                        'label' => 'Select Layout',
                        'name' => 'layout_type',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'grid' => 'Grid',
                            'carousel' => 'Carousel',
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'field_5b71363aae321',
                        'label' => 'Grid Layout',
                        'name' => 'grid_layout',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bc0811214c2a',
                                    'operator' => '==',
                                    'value' => 'grid',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'default-grid-layout' => 'Default Layout',
                            'grid-layout-1' => 'Grid Layout 1',
                            'grid-layout-2' => 'Grid Layout 2',
                            'grid-layout-3' => 'Grid Layout 3',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5bc0811214cb5',
                        'label' => 'Select Display',
                        'name' => 'display',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'image-above-content' => 'Image above content',
                            'image-overlay-content' => 'Image overlay content',
                            'image-left-content split-25-75' => 'Image left of content (25% | 75%)',
                            'image-left-content split-40-60' => 'Image left of content (40% | 60%)',
                            'image-left-content split-50-50' => 'Image left of content (50% | 50%)',
                            'image-right-content split-25-75' => 'Image right of content (75% | 25%)',
                            'image-right-content split-40-60' => 'Image right of content (60% | 40%)',
                            'image-right-content split-50-50' => 'Image right of content (50% | 50%)',
                            'image-left-content then-right split-50-50' => 'Image alternating left then right of content',
                            'image-right-content then-left split-50-50' => 'Image alternating right then left of content',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5bc0811214d41',
                        'label' => 'Per row',
                        'name' => 'per_row',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'medium-12' => '1 per row',
                            'medium-6' => '2 per row',
                            'medium-6 large-4' => '3 per row',
                            'medium-6 large-3' => '4 per row',
                        ),
                        'default_value' => array(
                            0 => 'medium-6 large-4',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_4ceca3229e113',
                        'label' => 'Auto Play',
                        'name' => 'slider_autoplay',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bc0811214c2a',
                                    'operator' => '==',
                                    'value' => 'carousel',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Enable',
                        'ui_off_text' => 'Disable',
                    ),
                     array(
                        'key' => 'field_5d155b0c45r32',
                        'label' => 'Slider Speed',
                        'name' => 'slider_speed',
                        'type' => 'number',
                        'instructions' => 'Please select transition speed between slides',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_4ceca3229e113',
                                    'operator' => '==',
                                    'value' => 1,
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 6,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => 'seconds',
                        'min' => 1,
                        'max' => 20,
                        'step' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5bc081119a8fc',
                'label' => 'Header',
                'name' => 'cpts_related_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5b90d65472f05',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119aaa0',
                'label' => 'Design',
                'name' => 'cpts_related_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119ab1f',
                'label' => 'Promotions',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc081119ac2d',
                'label' => 'Header',
                'name' => 'cpts_promotions_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5b90d65472f05',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119ad8b',
                'label' => 'Design',
                'name' => 'cpts_promotions_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119b5b0',
                'label' => 'FAQ',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc081119b621',
                'label' => 'Header',
                'name' => 'cpts_faq_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5b90d65472f05',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119b71b',
                'label' => 'Design',
                'name' => 'cpts_faq_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119a320',
                'label' => 'Testimonials',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc081119a39b',
                'label' => 'Layout',
                'name' => 'cpts_testimonials_layout',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5bc08111e19c1',
                        'label' => 'Select Layout',
                        'name' => 'layout_type',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'grid' => 'Grid',
                            'carousel' => 'Carousel',
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'field_5bc08111e1a3f',
                        'label' => 'Select Display',
                        'name' => 'testimonials_boxes_display',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'content-only' => 'Content Only',
                            'image-above-content' => 'Image above content',
                            'image-overlay-content' => 'Image overlay content',
                            'image-left-content split-25-75' => 'Image left of content (25% | 75%)',
                            'image-left-content split-40-60' => 'Image left of content (40% | 60%)',
                            'image-left-content split-50-50' => 'Image left of content (50% | 50%)',
                            'image-right-content split-25-75' => 'Image right of content (75% | 25%)',
                            'image-right-content split-60-40' => 'Image right of content (60% | 40%)',
                            'image-right-content split-50-50' => 'Image right of content (50% | 50%)',
                            'image-right-content split-40-60' => 'Image right of content (60% | 40%)',
                            'image-left-content then-right split-50-50' => 'Image alternating left then right of content',
                            'image-right-content then-left split-50-50' => 'Image alternating right then left of content',
                            'icon-above-content' => 'Icon above content',
                            'icon-left-content' => 'Icon left of content',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5bc08111e1abd',
                        'label' => 'Testimonials per row',
                        'name' => 'per_row',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'medium-12' => '1 per row',
                            'medium-6' => '2 per row',
                            'medium-6 large-4' => '3 per row',
                            'medium-6 large-3' => '4 per row',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5bc081119a415',
                'label' => 'Header',
                'name' => 'cpts_testimonials_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5b90d65472f05',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119a599',
                'label' => 'Design',
                'name' => 'cpts_testimonials_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc0811199dd8',
                'label' => 'Call to Action',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc0811199e65',
                'label' => 'Layout',
                'name' => 'cpts_cta_layout',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5bc08111cd0c4',
                        'label' => 'Select Display',
                        'name' => 'display',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'default-cta-layout' => 'Default Layout',
                            'cta-layout-1' => 'One Column Centered',
                            'cta-layout-2' => 'Content on Right',
                            'cta-layout-3' => 'Content on Left',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5bc0811199ee6',
                'label' => 'Header',
                'name' => 'cpts_cta_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'field_5b90d6e2e75ed',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc0811199fde',
                'label' => 'Design',
                'name' => 'cpts_cta_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bc081119b792',
                'label' => 'Global Element',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bc081119b803',
                'label' => 'Select Element',
                'name' => 'cpts_g_select',
                'type' => 'radio',
                'instructions' => 'To setup global elements and add content, please go to Site Settings',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-product-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 0,
        'description' => '',
    ));
    
    endif;