<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_571d78e917f50',
        'title' => 'Page Options',
        'fields' => array(
            array(
                'key' => 'field_57ad1a908d86f',
                'label' => 'Slider | Page Banner',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5adba3117e0b2',
                'label' => 'Slider | Page Banner',
                'name' => 'show_page_banner',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => 'Show',
                'ui_off_text' => 'Hide',
            ),
            array(
                'key' => 'field_5adec0ff67ec5',
                'label' => 'Banner Type',
                'name' => 'hero_banner_type',
                'type' => 'select',
                'instructions' => 'Select type of banner to display',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'page-banner' => 'Page Banner',
                    'gallery-background-banner' => 'Gallery Background',
                    'slider-carousel-banner' => 'Slider Carousel',
                    'background-with-slider' => 'Background Image w/ Gallery Slides',
                    'video-background-banner' => 'Video Background',
                ),
                'default_value' => array(
                    0 => 'page-banner',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5ab313d19be1f',
                'label' => 'Banner Text',
                'name' => 'f_hero_banner_content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'gallery-background-banner',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'background-with-slider',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'video-background-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5adba79c88912',
                'label' => 'Banner Button',
                'name' => 'hero_banner_button',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '!=',
                            'value' => 'page-banner',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '!=',
                            'value' => 'slider-carousel-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5adf3dfc751ec',
                        'label' => 'Button',
                        'name' => 'cta_button',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                    ),
                    array(
                        'key' => 'field_5b01d727aa5dc',
                        'label' => 'Button 2',
                        'name' => 'cta_button_2',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                    ),
                ),
            ),
            array(
                'key' => 'field_5ae8d57473eb5',
                'label' => 'Video Link',
                'name' => 'hero_banner_video_link',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'gallery-background-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ae8d65573eb6',
                        'label' => 'Video ID',
                        'name' => 'hero_banner_video_link_id',
                        'type' => 'text',
                        'instructions' => 'Enter YouTube video ID',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ae8d67473eb7',
                        'label' => 'Video Link Label',
                        'name' => 'hero_banner_video_link_label',
                        'type' => 'text',
                        'instructions' => 'Enter link text to display',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Watch Video',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5ab1f6f1f0f5a',
                'label' => 'Banner Slides',
                'name' => 'hero_image_slides',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'gallery-background-banner',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'background-with-slider',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'insert' => 'append',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'return_format' => 'array',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_5adec39f3d595',
                'label' => 'Slider Carousel',
                'name' => 'hero_banner_slider_carousel',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'slider-carousel-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5adec3fd3d596',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => 'Add Slide',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5adec3fd3d596',
                        'label' => 'Background Image',
                        'name' => 'hero_sc_background_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5adec4433d597',
                        'label' => 'Marketing Message',
                        'name' => 'hero_sc_marketing_message',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5c3c89d3ba58a',
                        'label' => 'Banner Button',
                        'name' => 'hero_sc_button',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5c3c89d3ba58b',
                                'label' => 'Button',
                                'name' => 'cta_button',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                            array(
                                'key' => 'field_5c3c89d3ba58c',
                                'label' => 'Button 2',
                                'name' => 'cta_button_2',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5c1afbe42a305',
                        'label' => 'Video Popup',
                        'name' => 'hero_sc_video',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5c1afc022a306',
                                'label' => 'Video Link',
                                'name' => 'hero_banner_video_link_id',
                                'type' => 'text',
                                'instructions' => 'Supported: Youtube & Vimeo',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5c1afc272a307',
                                'label' => 'Button Label',
                                'name' => 'hero_banner_video_link_label',
                                'type' => 'text',
                                'instructions' => 'Enter link text to display',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_5ae8d9898565e',
                'label' => 'Autoplay',
                'name' => 'hero_banner_carousel_autoplay',
                'type' => 'true_false',
                'instructions' => 'Autoplay carousel slider?',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'gallery-background-banner',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'slider-carousel-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5ae8d9999575e',
                'label' => 'Slider Arrow',
                'name' => 'hero_banner_carousel_arrow',
                'type' => 'true_false',
                'instructions' => 'Show carousel arrow?',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'gallery-background-banner',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'slider-carousel-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5ae8d9999685e',
                'label' => 'Slider Dots',
                'name' => 'hero_banner_carousel_dots',
                'type' => 'true_false',
                'instructions' => 'Show slider dots?',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'gallery-background-banner',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'slider-carousel-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5b075b0c36dc1',
                'label' => 'Slider Speed',
                'name' => 'hero_slider_carousel_speed',
                'type' => 'number',
                'instructions' => 'Please select transition speed between slides',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'gallery-background-banner',
                        ),
                        array(
                            'field' => 'field_5ae8d9898565e',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'slider-carousel-banner',
                        ),
                        array(
                            'field' => 'field_5ae8d9898565e',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 3,
                'placeholder' => '',
                'prepend' => '',
                'append' => 'seconds',
                'min' => 1,
                'max' => 10,
                'step' => '',
            ),
            array(
                'key' => 'field_5adec1f45ed4c',
                'label' => 'Background Video',
                'name' => 'f_hero_banner_video_background',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'video-background-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5adec26f5ed4d',
                        'label' => 'Video Type',
                        'name' => 'hero_banner_video_type',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'file' => 'File Upload',
                            'url' => 'YouTube or Vimeo URL',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'field_5adec31b5ed4e',
                        'label' => 'Background Video File',
                        'name' => 'hero_background_video_file',
                        'type' => 'file',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5adec26f5ed4d',
                                    'operator' => '==',
                                    'value' => 'file',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'library' => 'all',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_57ec6dd456f78',
                        'label' => 'Background Video URL',
                        'name' => 'hero_video_url',
                        'type' => 'url',
                        'instructions' => 'Enter a You Tube URL',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5adec26f5ed4d',
                                    'operator' => '==',
                                    'value' => 'url',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_57ec77f6b7ebc',
                        'label' => 'Video Fallback Image',
                        'name' => 'hero_video_fallback_image',
                        'type' => 'image',
                        'instructions' => 'This will be used as background image fallback for mobile and tablet',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5adba3117e0b2',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5848c4d8a112e',
                'label' => 'Banner Image',
                'name' => 'opt_banner_image',
                'type' => 'image',
                'instructions' => 'Upload an image below to override the default image for your theme.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'page-banner',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'background-with-slider',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5b3da9d237bf7',
                'label' => 'Page Title',
                'name' => 'page_banner_title',
                'type' => 'text',
                'instructions' => 'Enter a title below to override the default page title',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'page-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b3da9e937bf8',
                'label' => 'Page Subtitle',
                'name' => 'page_banner_subtitle',
                'type' => 'text',
                'instructions' => 'Add additional text we displays below the Page Title',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5adec0ff67ec5',
                            'operator' => '==',
                            'value' => 'page-banner',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b0628c3cad9a',
                'label' => 'Banner Height',
                'name' => 'page_banner_height',
                'type' => 'button_group',
                'instructions' => 'Select height of banner',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'default-height' => 'Default',
                    'short-banner' => 'Short',
                    'tall-banner' => 'Tall',
                    'full-screen-banner' => 'Full Screen',
                ),
                'allow_null' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5adbb7ee3abbf',
                'label' => 'Text Alignment',
                'name' => 'page_banner_text_alignment',
                'type' => 'button_group',
                'instructions' => 'Select text alignment',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'default-alignment' => 'Default',
                    'text-left' => 'Left',
                    'text-center' => 'Center',
                    'text-right' => 'Right',
                ),
                'allow_null' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5b56c1f322b0c',
                'label' => 'Background Filter',
                'name' => 'background_overlay',
                'type' => 'extended-color-picker',
                'instructions' => 'Add a filter over the image to make text stand out',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5adba3117e0b2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'rgba(10,0,0,0.5)',
                'color_palette' => 'rgba(10,0,0,0.5)',
                'hide_palette' => 0,
            ),
            array(
                'key' => 'field_5d3fdc0f1b59d',
                'label' => 'Menu',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5d3fdccf13482',
                'label' => 'Enable Custom menu',
                'name' => 'page_custom_menu',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5d3fdc251b59e',
                'label' => 'Menu',
                'name' => 'page_menu_item',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5d3fdccf13482',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'main-nav' => 'The Main Menu',
                    'footer-links' => 'Footer Primary Links',
                    'footer-links-2' => 'Footer Secondary Links',
                    'footer-links-3' => 'Footer Tertiary Links',
                    'top-menu' => 'Top Menu',
                ),
                'default_value' => array(
                ),
                'allow_null' => 1,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5c0f536g22dfc',
                'label' => 'Sidebar',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
              array(
                'key' => 'field_5c0f53bd43741',
                'label' => 'Enable Sidebar',
                'name' => 'page_sidebar',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5d79cb8c2833g',
                'label' => 'Location',
                'name' => 'page_sidebar_location',
                'type' => 'button_group',
                'instructions' => '',
                'required' => 0,
                 'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5c0f53bd43741',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'sidebar-left' => 'Left',
                    'sidebar-right' => 'Right',
                ),
                'allow_null' => 0,
                'default_value' => 'sidebar-right',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5c0f536f11fed',
                'label' => 'Form',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5c0f53bde3852',
                'label' => 'Enable Form',
                'name' => 'page_banner_display',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5c0f547fe3856',
                'label' => 'Options',
                'name' => 'form_options',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5c0f53bde3852',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                    'key' => 'field_5c833c8676342',
                    'label' => 'Form',
                    'name' => 'form_option',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'gravity-form' => 'Gravity Form',
                        'hicaliber_booking_form' => 'Hicaliber Booking Form',                        
                    ),
                    'allow_null' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                    array(
                        'key' => 'field_5c0f5492e3857',
                        'label' => 'Form',
                        'name' => 'form',
                        'type' => 'forms',
                        'instructions' => '',
                        'required' => 0,
                         'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5c833c8676342',
                                    'operator' => '==',
                                    'value' => 'gravity-form',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'post_object',
                        'allow_null' => 0,
                        'multiple' => 0,                        
                    ),
                    array(
                        'key' => 'field_5c1ae9cc8b07b',
                        'label' => 'Tab Index',
                        'name' => 'tab_index',
                        'type' => 'number',
                        'instructions' => 'Set the tab index with at least 20 interval.',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5c833c8676342',
                                    'operator' => '==',
                                    'value' => 'gravity-form',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                     array(
                        'key' => 'field_4e34debbed3b4',
                        'label' => 'Form Layout',
                        'name' => 'form_layout',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(                            
                            'form-layout-1' => 'Layout 1',
                            'form-layout-2' => 'Layout 2',                            
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5c0f557ee3858',
                        'label' => 'Position',
                        'name' => 'position',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'form-inline form-top' => 'Top',
                            'form-inline form-bottom' => 'Bottom',
                            'form-inline form-centered' => 'Centered',
                            'form-side form-right' => 'Right',
                            'form-side form-left' => 'Left',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    //   array(
                    //     'key' => 'field_5c0f3r22rerwf',
                    //     'label' => 'Description',
                    //     'name' => 'description',
                    //     'type' => 'wysiwyg',
                    //     'instructions' => '',
                    //     'required' => 0,
                    //     'conditional_logic' => 0,
                    //     'wrapper' => array(
                    //         'width' => '',
                    //         'class' => '',
                    //         'id' => '',
                    //     ),
                    //     'default_value' => '',
                    //     'tabs' => 'all',
                    //     'toolbar' => 'full',
                    //     'media_upload' => 1,
                    //     'delay' => 0,
                    // ),
                    array(
                        'key' => 'field_5c0f55c4e3859',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5c0f55cbe385a',
                        'label' => 'Blurb',
                        'name' => 'blurb',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                ),
            ),
// array(
//             'key' => 'field_5be91b54dde93',
//             'label' => 'Show Booking Form',
//             'name' => 'show_booking_form',
//             'type' => 'true_false',
//             'instructions' => '',
//             'required' => 0,
//             'conditional_logic' => 0,
//             'wrapper' => array(
//                 'width' => '',
//                 'class' => '',
//                 'id' => '',
//             ),
//             'message' => '',
//             'default_value' => 0,
//             'ui' => 1,
//             'ui_on_text' => '',
//             'ui_off_text' => '',
//         ),
//         array(
//             'key' => 'field_5bfe73a850d23',
//             'label' => 'Search Type',
//             'name' => 'search_form_selection_type',
//             'type' => 'button_group',
//             'instructions' => '',
//             'required' => 0,
//             'conditional_logic' => array(
//                 array(
//                     array(
//                         'field' => 'field_5be91b54dde93',
//                         'operator' => '==',
//                         'value' => '1',
//                     ),
//                 ),
//             ),
//             'wrapper' => array(
//                 'width' => '',
//                 'class' => '',
//                 'id' => '',
//             ),
//             'choices' => array(
//                 'properties' => 'Properties',
//                 'locations' => 'Locations',
//             ),
//             'allow_null' => 0,
//             'default_value' => '',
//             'layout' => 'horizontal',
//             'return_format' => 'value',
//         ),
//         array(
//             'key' => 'field_5bed633ea1050',
//             'label' => 'Banner Layout',
//             'name' => 'hero_booking_layout',
//             'type' => 'select',
//             'instructions' => '',
//             'required' => 0,
//             'conditional_logic' => array(
//                 array(
//                     array(
//                         'field' => 'field_5be91b54dde93',
//                         'operator' => '==',
//                         'value' => '1',
//                     ),
//                 ),
//             ),
//             'wrapper' => array(
//                 'width' => '',
//                 'class' => '',
//                 'id' => '',
//             ),
//             'choices' => array(
//                 'hero-layout-1' => 'Layout 1',
//                 'hero-layout-2' => 'Layout 2',
//             ),
//             'default_value' => array(
//             ),
//             'allow_null' => 1,
//             'multiple' => 0,
//             'ui' => 0,
//             'return_format' => 'value',
//             'ajax' => 0,
//             'placeholder' => '',
//         ),
//         array(
//             'key' => 'field_5bf876f8f84ca',
//             'label' => 'Form Position',
//             'name' => 'hero_booking_position',
//             'type' => 'select',
//             'instructions' => '',
//             'required' => 0,
//             'conditional_logic' => array(
//                 array(
//                     array(
//                         'field' => 'field_5be91b54dde93',
//                         'operator' => '==',
//                         'value' => '1',
//                     ),
//                 ),
//             ),
//             'wrapper' => array(
//                 'width' => '',
//                 'class' => '',
//                 'id' => '',
//             ),
//             'choices' => array(
//                 'hero-form-inline form-bottom' => 'Bottom',
//                 'hero-form-inline form-centered' => 'Centered',
//                 'hero-form-side form-right' => 'Right',
//                 'hero-form-side form-left' => 'Left',
//             ),
//             'default_value' => array(
//             ),
//             'allow_null' => 1,
//             'multiple' => 0,
//             'ui' => 0,
//             'return_format' => 'value',
//             'ajax' => 0,
//             'placeholder' => '',
//         ),
//         array(
//             'key' => 'field_5bf86c82bdf22',
//             'label' => 'Form Title',
//             'name' => 'hero_booking_title',
//             'type' => 'text',
//             'instructions' => '',
//             'required' => 0,
//             'conditional_logic' => array(
//                 array(
//                     array(
//                         'field' => 'field_5be91b54dde93',
//                         'operator' => '==',
//                         'value' => '1',
//                     ),
//                 ),
//             ),
//             'wrapper' => array(
//                 'width' => '',
//                 'class' => '',
//                 'id' => '',
//             ),
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'maxlength' => '',
//         ),
//          array(
//             'key' => 'field_5c0f67cbe395b',
//             'label' => 'Blurb',
//             'name' => 'hero_booking_blurb',
//             'type' => 'textarea',
//             'instructions' => '',
//             'required' => 0,
//             'conditional_logic' => array(
//                 array(
//                     array(
//                         'field' => 'field_5be91b54dde93',
//                         'operator' => '==',
//                         'value' => '1',
//                     ),
//                 ),
//             ),
//             'wrapper' => array(
//                 'width' => '',
//                 'class' => '',
//                 'id' => '',
//             ),
//             'default_value' => '',
//             'placeholder' => '',
//             'maxlength' => '',
//             'rows' => '',
//             'new_lines' => '',
//         ),
//         array(
//             'key' => 'field_5bff3b8229138',
//             'label' => 'Tracking Code',
//             'name' => 'property_hsite_tracking_code',
//             'type' => 'text',
//             'instructions' => 'Enter a tracking code to track bookings made via this page.',
//             'required' => 0,
//              'conditional_logic' => array(
//                 array(
//                     array(
//                         'field' => 'field_5be91b54dde93',
//                         'operator' => '==',
//                         'value' => '1',
//                     ),
//                 ),
//             ),
//             'wrapper' => array(
//                 'width' => '',
//                 'class' => '',
//                 'id' => '',
//             ),
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'maxlength' => '',
//         ),
            array(
                'key' => 'field_5adc67202de15',
                'label' => 'Advanced Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5adc675a2de16',
                'label' => 'Custom CSS Classes',
                'name' => 'page_custom_css',
                'type' => 'text',
                'instructions' => 'The custom CSS classes entered here are added to the page body.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(           
            array(
                array(
                    'param' => 'page_type',
                    'operator' => '==',
                    'value' => 'front_page',
                ),
            ),
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'location_post',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'location_page',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'ac-properties',
                ),
            ), 
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                ),
            ),            
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'ac-promotions',
                ),
            ),             
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'room-type',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'events',
                ),
            ),                                                
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'template-page-builder.php',
                ),
            ),
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'template-cpt-archive.php',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'project',
                ),
            ),
             array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'gallery',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
    
    endif;