<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5bac774f24f52',
        'title' => 'Page Element Layout',
        'fields' => array(        
                array(
                    'key' => 'field_5c5a7900c2555',
                    'label' => 'Select Layout',
                    'name' => 'peh_layout_type',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'grid' => 'Grid',
                        'carousel' => 'Carousel',
                    ),
                    'allow_null' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                 array(
                    'key' => 'field_6bs3262563214',
                    'label' => 'Grid Layout',
                    'name' => 'peh_grid_layout',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5c5a7900c2555',
                                'operator' => '==',
                                'value' => 'grid',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'default-grid-layout' => 'Default Layout',
                        'grid-layout-1' => 'Grid Layout 1',
                        'grid-layout-2' => 'Grid Layout 2',
                        'grid-layout-3' => 'Grid Layout 3',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5c5a3467d1166',
                    'label' => 'Select Display',
                    'name' => 'display',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'content-only' => 'Content Only',
                        'image-above-content' => 'Image above content',
                        'image-overlay-content' => 'Image overlay content',
                        'image-left-content split-25-75' => 'Image left of content (25% | 75%)',
                        'image-left-content split-40-60' => 'Image left of content (40% | 60%)',
                        'image-left-content split-50-50' => 'Image left of content (50% | 50%)',
                        'image-left-content split-60-40' => 'Image left of content (60% | 40%)',
                        'image-right-content split-25-75' => 'Image right of content (75% | 25%)',
                        'image-right-content split-40-60' => 'Image right of content (60% | 40%)',
                        'image-right-content split-50-50' => 'Image right of content (50% | 50%)',
                        'image-left-content then-right split-50-50' => 'Image alternating left then right of content',
                        'image-right-content then-left split-50-50' => 'Image alternating right then left of content',
                        'icon-above-content' => 'Icon above content',
                        'icon-left-content' => 'Icon left of content',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5d55322215555',
                    'label' => 'Post per row',
                    'name' => 'per_row',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'medium-12' => '1 per row',
                        'medium-6' => '2 per row',
                        'medium-6 large-4' => '3 per row',
                        'medium-6 large-3' => '4 per row',
                        'medium-4 large-2_4' => '5 per row',
                        'medium-4 large-2' => '6 per row',
                    ),
                    'default_value' => array(
                        0 => 'medium-6 large-4',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5adba3333222125',
                    'label' => 'Auto Play',
                    'name' => 'slider_autoplay',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5c5a7900c2555',
                                'operator' => '==',
                                'value' => 'carousel',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => 'Enable',
                    'ui_off_text' => 'Disable',
                ),
                 array(
                    'key' => 'field_5adb432244444',
                    'label' => 'Slider Speed',
                    'name' => 'slider_speed',
                    'type' => 'number',
                    'instructions' => 'Please select transition speed between slides',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5adba3333222125',
                                'operator' => '==',
                                'value' => 1,
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 6,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => 'seconds',
                    'min' => 1,
                    'max' => 20,
                    'step' => '',
                ),                
          ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 0,
        'description' => '',
    ));
    
    endif;