<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5bb61c7558ea4',
        'title' => 'Page Content Builder Columns',
        'fields' => array(
            array(
                'key' => 'field_5bb61c62ab401',
                'label' => 'Page Sections',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bb61c82ab402',
                'label' => 'Instructions',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Select which page columns you would like to display on the page. A Content tab will display after selecting page columns to allow you to customize it.',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5bb61ca2ab403',
                'label' => 'Column Type',
                'name' => 'column_type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_5bb61cd7ab404',
                'label' => 'Column Content',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5bb61ce3ab405',
                'label' => 'Header',
                'name' => 'columns_header',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5b90d65472f05',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bb61dcffed7b',
                'label' => 'Columns',
                'name' => 'cc_columns',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5bb61e0febc6b',
                        'label' => '1/1 Column',
                        'name' => 'first_column',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                     array(
                        'key' => 'field_5bb61e0gecd7c',
                        'label' => '1/2 Column',
                        'name' => 'second_column',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                         'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bb61ca2ab403',
                                    'operator' => '!=',
                                    'value' => 'full-column',
                                ),
                            ),                           
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5bb61e0gfde8d',
                        'label' => '1/3 Column',
                        'name' => 'third_column',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                         'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5bb61ca2ab403',
                                    'operator' => '==',
                                    'value' => 'three-columns',
                                ),
                            ),  
                             array(
                                array(
                                    'field' => 'field_5bb61ca2ab403',
                                    'operator' => '==',
                                    'value' => 'four-columns',
                                ),
                            ),                          
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                     array(
                        'key' => 'field_5bb61e0gfex9e',
                        'label' => '1/4 Column',
                        'name' => 'fourth_column',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                         'conditional_logic' => array(                          
                             array(
                                array(
                                    'field' => 'field_5bb61ca2ab403',
                                    'operator' => '==',
                                    'value' => 'four-columns',
                                ),
                            ),                          
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                ),
               
            ),
           
            array(
                'key' => 'field_5bb61d1fab406',
                'label' => 'Footer',
                'name' => 'columns_footer',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bb1882833bfa',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
            array(
                'key' => 'field_5bb61d46ab407',
                'label' => 'Design',
                'name' => 'columns_design',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'group_5bac772faef77',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 0,
        'description' => '',
    ));
    
    endif;