<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c1306ac4a8a6',
	'title' => 'Post Settings',
	'fields' => array(
		array(
			'key' => 'field_6dde159a7be0d',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cce159a6ad9e',
			'label' => 'Sidebar',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_432d1239416e5',
			'label' => 'Post Pages',
			'name' => 'post_sidebar',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5ebgcf7a42424',
					'label' => 'Single Page',
					'name' => 'post_sp_sidebar',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'none' => 'None',
						'has-sidebar-left' => 'Left',
						'has-sidebar-right' => 'Right',
						'has-sidebar-both' => 'Both',
					),
					'allow_null' => 0,
					'default_value' => 'radio',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5bc13abee133d',
					'label' => 'Left Sidebar',
					'name' => 'sp_left_sidebar',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ebgcf7a42424',
								'operator' => '==',
								'value' => 'has-sidebar-left',
							),
						),
						array(
							array(
								'field' => 'field_5ebgcf7a42424',
								'operator' => '==',
								'value' => 'has-sidebar-both',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'sidebar-options',
						'id' => '',
					),
					'choices' => array(
						'sidebar1' => 'Sidebar 1',
						'sidebar2' => 'Sidebar 2',
						'offcanvas' => 'Offcanvas',
					),
					'default_value' => 0,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5bc13abdd213f',
					'label' => 'Right Sidebar',
					'name' => 'sp_right_sidebar',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ebgcf7a42424',
								'operator' => '==',
								'value' => 'has-sidebar-right',
							),
						),
						array(
							array(
								'field' => 'field_5ebgcf7a42424',
								'operator' => '==',
								'value' => 'has-sidebar-both',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'sidebar-options',
						'id' => '',
					),
					'choices' => array(
						'sidebar1' => 'Sidebar 1',
						'sidebar2' => 'Sidebar 2',
						'offcanvas' => 'Offcanvas',
					),
					'default_value' => 0,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_6dchef7c73436',
					'label' => 'Archive Page',
					'name' => 'post_ap_sidebar',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'none' => 'None',
						'has-sidebar-left' => 'Left',
						'has-sidebar-right' => 'Right',
						'has-sidebar-both' => 'Both',
					),
					'allow_null' => 0,
					'default_value' => 'radio',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5bc13abee124e',
					'label' => 'Left Sidebar',
					'name' => 'ap_left_sidebar',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6dchef7c73436',
								'operator' => '==',
								'value' => 'has-sidebar-left',
							),
						),
						array(
							array(
								'field' => 'field_6dchef7c73436',
								'operator' => '==',
								'value' => 'has-sidebar-both',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'sidebar-options',
						'id' => '',
					),
					'choices' => array(
						'sidebar1' => 'Sidebar 1',
						'sidebar2' => 'Sidebar 2',
						'offcanvas' => 'Offcanvas',
					),
					'default_value' => 0,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5bc13abdd214e',
					'label' => 'Right Sidebar',
					'name' => 'ap_right_sidebar',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6dchef7c73436',
								'operator' => '==',
								'value' => 'has-sidebar-right',
							),
						),
						array(
							array(
								'field' => 'field_6dchef7c73436',
								'operator' => '==',
								'value' => 'has-sidebar-both',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'sidebar-options',
						'id' => '',
					),
					'choices' => array(
						'sidebar1' => 'Sidebar 1',
						'sidebar2' => 'Sidebar 2',
						'offcanvas' => 'Offcanvas',
					),
					'default_value' => 0,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_4ecedf9c83647',
					'label' => 'Category Page',
					'name' => 'post_cp_sidebar',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'none' => 'None',
						'has-sidebar-left' => 'Left',
						'has-sidebar-right' => 'Right',
						'has-sidebar-both' => 'Both',
					),
					'allow_null' => 0,
					'default_value' => 'radio',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5bc13abee113f',
					'label' => 'Left Sidebar',
					'name' => 'cp_left_sidebar',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_4ecedf9c83647',
								'operator' => '==',
								'value' => 'has-sidebar-left',
							),
						),
						array(
							array(
								'field' => 'field_4ecedf9c83647',
								'operator' => '==',
								'value' => 'has-sidebar-both',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'sidebar-options',
						'id' => '',
					),
					'choices' => array(
						'sidebar1' => 'Sidebar 1',
						'sidebar2' => 'Sidebar 2',
						'offcanvas' => 'Offcanvas',
					),
					'default_value' => 0,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5bc13abdd225f',
					'label' => 'Right Sidebar',
					'name' => 'cp_right_sidebar',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_4ecedf9c83647',
								'operator' => '==',
								'value' => 'has-sidebar-right',
							),
						),
						array(
							array(
								'field' => 'field_4ecedf9c83647',
								'operator' => '==',
								'value' => 'has-sidebar-both',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'sidebar-options',
						'id' => '',
					),
					'choices' => array(
						'sidebar1' => 'Sidebar 1',
						'sidebar2' => 'Sidebar 2',
						'offcanvas' => 'Offcanvas',
					),
					'default_value' => 0,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_4ecedf9c94758',
					'label' => 'Tag Page',
					'name' => 'post_tp_sidebar',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'none' => 'None',
						'has-sidebar-left' => 'Left',
						'has-sidebar-right' => 'Right',
						'has-sidebar-both' => 'Both',
					),
					'allow_null' => 0,
					'default_value' => 'radio',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
		array(
			'key' => 'field_5c1307c9da33b',
			'label' => 'Single Page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d1c0239527f6',
			'label' => 'Banner Options',
			'name' => 'post_single_banner_options',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_387e1a019e971',
					'label' => 'Banner Display',
					'name' => 'show_page_banner',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Show',
					'ui_off_text' => 'Hide',
				),
				array(
					'key' => 'field_578c36efwce50',
					'label' => 'Banner Image',
					'name' => 'post_single_page_banner',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_387e1a019e971',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5af94261b2861',
					'label' => 'Title Location',
					'name' => 'title_location',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_387e1a019e971',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'title-above-image' => 'Above Featured Image',
						'title-below-image' => 'Below Featured Image',
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
		array(
			'key' => 'field_5c652cc437864',
			'label' => 'Post Meta Options',
			'name' => 'single_post_meta_options',
			'type' => 'checkbox',
			'instructions' => 'Check post meta data to display on the page',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'date' => 'Date',
				'author' => 'Author',
				'category' => 'Category',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'acfe_flexible_advanced' => 0,
			'acfe_flexible_stylised_button' => 0,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_disable_ajax_title' => 0,
			'acfe_flexible_layouts_thumbnails' => 0,
			'acfe_flexible_layouts_settings' => 0,
			'acfe_flexible_layouts_ajax' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_placeholder' => 0,
			'acfe_flexible_title_edition' => 0,
			'acfe_flexible_clone' => 0,
			'acfe_flexible_copy_paste' => 0,
			'acfe_flexible_toggle' => 0,
			'acfe_flexible_close_button' => 0,
			'acfe_flexible_remove_add_button' => 0,
			'acfe_flexible_remove_duplicate_button' => 0,
			'acfe_flexible_remove_delete_button' => 0,
			'acfe_flexible_lock' => 0,
			'acfe_flexible_modal_edition' => 0,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => false,
				'acfe_flexible_modal_title' => false,
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => false,
			),
			'acfe_flexible_layouts_state' => '',
			'acfe_flexible_layouts_remove_collapse' => 0,
			'key' => 'field_5c1307d7da33c',
			'label' => 'Elements',
			'name' => 'ps_sp_elements',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5bc431288a48f' => array(
					'key' => '5bc431288a48f',
					'name' => 'related',
					'label' => 'Related',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bedfa77f182f',
							'label' => 'Related Layout',
							'name' => 'ps_sp_related_layout',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b8e79de0c57b',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc081119b8fe',
							'label' => 'Header',
							'name' => 'ps_sp_related_header',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5b90d65472f05',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc081119b9fe',
							'label' => 'Content Options',
							'name' => 'ps_sp_related_content_option',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5c652dd224353',
								1 => 'field_5adbcd69a0642',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bedfa77f082e',
							'label' => 'Related Design',
							'name' => 'ps_related_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b8e79de0c5a7',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'5c13077f04123' => array(
					'key' => '5c13077f04123',
					'name' => 'global_element',
					'label' => 'Global Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c1307d7da33d',
							'label' => 'Select Element',
							'name' => 'pe_g_select',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
		),
		array(
			'key' => 'field_5c1305c9cb44c',
			'label' => 'Category Page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d1c0238322f6',
			'label' => 'Banner Options',
			'name' => 'pc_banner_option',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_48bd1a913d992',
					'label' => 'Banner Display',
					'name' => 'show_page_banner',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Show',
					'ui_off_text' => 'Hide',
				),
				array(
					'key' => 'field_67ad1a9133238',
					'label' => 'Default Banner Image',
					'name' => 'pc_default_banner',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_48bd1a913d992',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5b3da9d232rd5',
					'label' => 'Banner height',
					'name' => 'banner_height',
					'type' => 'button_group',
					'instructions' => 'Select height of banner',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_48bd1a913d992',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'default-height' => 'Default',
						'short-banner' => 'Short',
						'tall-banner' => 'Tall',
						'full-screen-banner' => 'Full Screen',
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5b3da9d6132s3',
					'label' => 'Text Alignment',
					'name' => 'banner_alignment',
					'type' => 'button_group',
					'instructions' => 'Select text alignment',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_48bd1a913d992',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'default-alignment' => 'Default',
						'text-left' => 'Left',
						'text-center' => 'Center',
						'text-right' => 'Right',
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5b3da93213b3c',
					'label' => 'Background Filter',
					'name' => 'background_overlay',
					'type' => 'extended-color-picker',
					'instructions' => 'Add a filter over the image to make text stand out',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_48bd1a913d992',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'rgba(10,0,0,0.5)',
					'color_palette' => 'rgba(10,0,0,0.5)',
					'hide_palette' => 0,
				),
			),
		),
		array(
			'acfe_flexible_advanced' => 0,
			'acfe_flexible_stylised_button' => 0,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_disable_ajax_title' => 0,
			'acfe_flexible_layouts_thumbnails' => 0,
			'acfe_flexible_layouts_settings' => 0,
			'acfe_flexible_layouts_ajax' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_placeholder' => 0,
			'acfe_flexible_title_edition' => 0,
			'acfe_flexible_clone' => 0,
			'acfe_flexible_copy_paste' => 0,
			'acfe_flexible_toggle' => 0,
			'acfe_flexible_close_button' => 0,
			'acfe_flexible_remove_add_button' => 0,
			'acfe_flexible_remove_duplicate_button' => 0,
			'acfe_flexible_remove_delete_button' => 0,
			'acfe_flexible_lock' => 0,
			'acfe_flexible_modal_edition' => 0,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => false,
				'acfe_flexible_modal_title' => false,
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => false,
			),
			'acfe_flexible_layouts_state' => '',
			'acfe_flexible_layouts_remove_collapse' => 0,
			'key' => 'field_6cd6265ed1d66',
			'label' => 'Page Element Builder',
			'name' => 'post_cat_element_builder',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'4bc42d1b5434' => array(
					'key' => '4bc42d1b5434',
					'name' => 'description',
					'label' => 'Description',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bc42d0b1d5d3',
							'label' => 'Descriptions',
							'name' => 'description',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b8e79de0c3a1',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'5bc43128d1233' => array(
					'key' => '5bc43128d1233',
					'name' => 'post',
					'label' => 'Post Listing',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b44311342431',
							'label' => 'Layout',
							'name' => 'cpts_post_list_layout',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5bc431223432',
									'label' => 'Post Layout',
									'name' => 'post_list',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_6bs1363bbe342',
										1 => 'field_5c5a7900d68c8',
										2 => 'field_5c5a7900d68c9',
									),
									'display' => 'seamless',
									'layout' => '',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
							),
						),
						array(
							'key' => 'field_5bc4312439194',
							'label' => 'Content',
							'name' => 'cpts_post_list_option',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5bc4312990123',
									'label' => 'Featured',
									'name' => 'featured_post',
									'type' => 'true_false',
									'instructions' => 'Display Featured Post',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5bd1332889404',
									'label' => 'Content to Display',
									'name' => 'project_content_to_display',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'description' => 'Description',
										'button' => 'Button',
									),
									'allow_custom' => 0,
									'save_custom' => 0,
									'default_value' => array(
										0 => 'description',
										1 => 'button',
									),
									'layout' => 'vertical',
									'toggle' => 0,
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5bc4312421331',
									'label' => 'Content',
									'name' => 'post_list_content',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_5c652dd224353',
										1 => 'field_5ad963aef1102',
									),
									'display' => 'seamless',
									'layout' => '',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
							),
						),
						array(
							'key' => 'field_5bc4311434313',
							'label' => 'Design',
							'name' => 'post_list_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b8e79de0c3a1',
							),
							'display' => 'seamless',
							'layout' => '',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'5bc433d38930b' => array(
					'key' => '5bc433d38930b',
					'name' => 'global_element',
					'label' => 'Global Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bc43fd38941c',
							'label' => 'Call to Actionsdadf',
							'name' => 'call_to_action',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5bac2c795ee2e',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
		),
		array(
			'key' => 'field_5fabf6f18bba4',
			'label' => 'Tag Page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5fabf7118bba5',
			'label' => 'Banner Options',
			'name' => 'pt_banner_option',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_5fabf7118bba6',
					'label' => 'Banner Display',
					'name' => 'show_page_banner',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Show',
					'ui_off_text' => 'Hide',
				),
				array(
					'key' => 'field_5fabf7118bba7',
					'label' => 'Default Banner Image',
					'name' => 'pc_default_banner',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fabf7118bba6',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_uploader' => 'wp',
					'acfe_thumbnail' => 0,
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5fabf7118bba8',
					'label' => 'Banner height',
					'name' => 'banner_height',
					'type' => 'button_group',
					'instructions' => 'Select height of banner',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fabf7118bba6',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'default-height' => 'Default',
						'short-banner' => 'Short',
						'tall-banner' => 'Tall',
						'full-screen-banner' => 'Full Screen',
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5fabf7118bba9',
					'label' => 'Text Alignment',
					'name' => 'banner_alignment',
					'type' => 'button_group',
					'instructions' => 'Select text alignment',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fabf7118bba6',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'default-alignment' => 'Default',
						'text-left' => 'Left',
						'text-center' => 'Center',
						'text-right' => 'Right',
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5fabf7118bbaa',
					'label' => 'Background Filter',
					'name' => 'background_overlay',
					'type' => 'extended-color-picker',
					'instructions' => 'Add a filter over the image to make text stand out',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fabf7118bba6',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33.33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 'rgba(10,0,0,0.5)',
					'color_palette' => 'rgba(10,0,0,0.5)',
					'hide_palette' => 0,
				),
			),
		),
		array(
			'acfe_flexible_advanced' => 0,
			'acfe_flexible_stylised_button' => 0,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_disable_ajax_title' => 0,
			'acfe_flexible_layouts_thumbnails' => 0,
			'acfe_flexible_layouts_settings' => 0,
			'acfe_flexible_layouts_ajax' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_placeholder' => 0,
			'acfe_flexible_title_edition' => 0,
			'acfe_flexible_clone' => 0,
			'acfe_flexible_copy_paste' => 0,
			'acfe_flexible_toggle' => 0,
			'acfe_flexible_close_button' => 0,
			'acfe_flexible_remove_add_button' => 0,
			'acfe_flexible_remove_duplicate_button' => 0,
			'acfe_flexible_remove_delete_button' => 0,
			'acfe_flexible_lock' => 0,
			'acfe_flexible_modal_edition' => 0,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => false,
				'acfe_flexible_modal_title' => false,
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => false,
			),
			'acfe_flexible_layouts_state' => '',
			'acfe_flexible_layouts_remove_collapse' => 0,
			'key' => 'field_5fabf7368bbab',
			'label' => 'Page Element Builder',
			'name' => 'post_tag_element_builder',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layouts' => array(
				'4bc42d1b5434' => array(
					'key' => '4bc42d1b5434',
					'name' => 'description',
					'label' => 'Description',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fabf7368bbac',
							'label' => 'Descriptions',
							'name' => 'description',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'field_5b8e79de0c3a1',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'5bc43128d1233' => array(
					'key' => '5bc43128d1233',
					'name' => 'post',
					'label' => 'Post Listing',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fabf7368bbad',
							'label' => 'Layout',
							'name' => 'cpts_post_list_layout',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'layout' => 'block',
							'acfe_seamless_style' => 0,
							'acfe_group_modal' => 0,
							'acfe_group_modal_close' => 0,
							'acfe_group_modal_button' => '',
							'acfe_group_modal_size' => 'large',
							'sub_fields' => array(
								array(
									'key' => 'field_5fabf7368bbae',
									'label' => 'Post Layout',
									'name' => 'post_list',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'clone' => array(
										0 => 'field_6bs1363bbe342',
										1 => 'field_5c5a7900d68c8',
										2 => 'field_5c5a7900d68c9',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
									'acfe_seamless_style' => 0,
									'acfe_clone_modal' => 0,
									'acfe_clone_modal_close' => 0,
									'acfe_clone_modal_button' => '',
									'acfe_clone_modal_size' => 'large',
								),
							),
						),
						array(
							'key' => 'field_5fabf7368bbaf',
							'label' => 'Content',
							'name' => 'cpts_post_list_option',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'layout' => 'block',
							'acfe_seamless_style' => 0,
							'acfe_group_modal' => 0,
							'acfe_group_modal_close' => 0,
							'acfe_group_modal_button' => '',
							'acfe_group_modal_size' => 'large',
							'sub_fields' => array(
								array(
									'key' => 'field_5fabf7368bbb0',
									'label' => 'Featured',
									'name' => 'featured_post',
									'type' => 'true_false',
									'instructions' => 'Display Featured Post',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5fabf7368bbb1',
									'label' => 'Content to Display',
									'name' => 'project_content_to_display',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'choices' => array(
										'description' => 'Description',
										'button' => 'Button',
									),
									'allow_custom' => 0,
									'save_custom' => 0,
									'default_value' => array(
										0 => 'description',
										1 => 'button',
									),
									'layout' => 'vertical',
									'toggle' => 0,
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5fabf7368bbb2',
									'label' => 'Content',
									'name' => 'post_list_content',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'clone' => array(
										0 => 'field_5c652dd224353',
										1 => 'field_5ad963aef1102',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
									'acfe_seamless_style' => 0,
									'acfe_clone_modal' => 0,
									'acfe_clone_modal_close' => 0,
									'acfe_clone_modal_button' => '',
									'acfe_clone_modal_size' => 'large',
								),
							),
						),
						array(
							'key' => 'field_5fabf7368bbb3',
							'label' => 'Design',
							'name' => 'post_list_design',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'field_5b8e79de0c3a1',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'5bc433d38930b' => array(
					'key' => '5bc433d38930b',
					'name' => 'global_element',
					'label' => 'Global Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5fabf7368bbb4',
							'label' => 'Call to Actionsdadf',
							'name' => 'call_to_action',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'field_5bac2c795ee2e',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_category' => false,
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-post-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

endif;
?>