<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5bee1586be04a',
	'title' => 'Location Categories Settings',
	'fields' => array (
        array(
            'key' => 'field_5d1b1826e7299',
            'label' => 'Category Image/Icon',
            'name' => 'cat_map_image_icon',
            'type' => 'image',
            'instructions' => 'Image or icon that represent this category',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
		array(
            'key' => 'field_5b0b1826e71ae',
            'label' => 'Category Map Default Marker',
            'name' => 'cat_map_default_marker',
            'type' => 'image',
            'instructions' => 'This will be used as the default marker image on the Location Map for location of this category. Leave this empty to use the default marker on the Location Settings',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5b0b1826e71af',
            'label' => 'Category Map Selected Marker',
            'name' => 'cat_map_selected_marker',
            'type' => 'image',
            'instructions' => 'This will be used as the marker image on the Location Map when a location of this category is selected. Leave this empty to use the marker on the Location Settings',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'location_cat',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;