<?php

if( function_exists('acf_add_local_field_group') ):

$settings = array (
	'key' => 'group_5bedfa77d2978',
	'title' => 'Location Settings',
	'fields' => array (
		array (
			'key' => 'field_5bedfa77d8ff5',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bed2e7201332',
			'label' => 'Slug',
			'name' => 'ls_location_slug',
			'type' => 'text',
			'instructions' => 'Please make sure to save <a href=\'options-permalink.php\' target=\'_blank\'>permalink</a> settings after you update this field. Please also take note that if slug have equivalent page slug, the archive will be automatically disabled.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'location',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bee756e5d0e1',
			'label' => 'Enable Franchisee Location',
			'name' => 'ls_location_post',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => 'This will enabled Location Post CPT',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
		),
		array (
			'key' => 'field_5bee756f5d1e1',
			'label' => 'Enable Custom Page Design',
			'name' => 'ls_location_custom_design',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => 'This will enabled customization of Location Pages and Post Header and Footer Design',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
		),
		array(
			'key' => 'field_5afdee4b4dae5',
			'label' => 'Header',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bee756f5d1e1',
						'operator' => '==',
						'value' => 1,
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b001bf00386a',
			'label' => 'Top Header',
			'name' => 'ls_show_top_header',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
			'key' => 'field_5b01e6f973187',
			'label' => 'Top Header Columns',
			'name' => 'ls_top_header_cols',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b001bf00386a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'one-column' => 'One Column',
				'two-column' => 'Two Columns',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b01e76873188',
			'label' => 'Column One',
			'name' => 'ls_top_header_col_1',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b001bf00386a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5b01e7a273189',
					'label' => 'Select Element',
					'name' => 'element',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'contact-information' => 'Contact Information',
						'social-media' => 'Social Media Links',
						'top-menu' => 'Top Menu',
						'text' => 'Text',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5b01e89f7318c',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5b01e7a273189',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_5b01e8e97318d',
			'label' => 'Column Two',
			'name' => 'ls_top_header_col_2',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5b001bf00386a',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5b01e6f973187',
						'operator' => '==',
						'value' => 'two-column',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5b01e8e97318e',
					'label' => 'Select Element',
					'name' => 'element',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'contact-information' => 'Contact Information',
						'social-media' => 'Social Media Links',
						'top-menu' => 'Top Menu',
						'text' => 'Text',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5b01e8e973190',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5b01e8e97318e',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_5b0669915635d',
			'label' => 'Sticky Header',
			'name' => 'ls_fix_header',
			'type' => 'true_false',
			'instructions' => 'Fix header to top of page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_5bedfa77d7bf3',
			'label' => 'Sidebar',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
            'key' => 'field_432d1239426e6',
            'label' => 'Location Pages',
            'name' => 'location_sidebar',
            'type' => 'group',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array (
                array(
                    'key' => 'field_5ebgcf7a43425',
                    'label' => 'Single Page',
                    'name' => 'post_sp_sidebar',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'none' => 'None',
                        'has-sidebar-left' => 'Left',
                        'has-sidebar-right' => 'Right',
                        'has-sidebar-both' => 'Both',
                    ),
                    'allow_null' => 0,
                    'default_value' => 'radio',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_5bc13abee233e',
                    'label' => 'Left Sidebar',
                    'name' => 'sp_left_sidebar',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_5ebgcf7a43425',
                                'operator' => '==',
                                'value' => 'has-sidebar-left',
                            ),
                        ),   
                        array (
                            array (
                                'field' => 'field_5ebgcf7a43425',
                                'operator' => '==',
                                'value' => 'has-sidebar-both',
                            ),
                        ),                       
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => 'sidebar-options',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => 0,
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5bc13abdd3140',
                    'label' => 'Right Sidebar',
                    'name' => 'sp_right_sidebar',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_5ebgcf7a43425',
                                'operator' => '==',
                                'value' => 'has-sidebar-right',
                            ),
                        ),
                        array (
                            array (
                                'field' => 'field_5ebgcf7a43425',
                                'operator' => '==',
                                'value' => 'has-sidebar-both',
                            ),
                        ),                        
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => 'sidebar-options',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => 0,
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),                
            ),
        ),
		array (
			'key' => 'field_5bedfa77d7ef5',
			'label' => 'Single Page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5bee756e5cfd1',
			'label' => 'Single Page',
			'name' => 'ls_single_page',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
		),
		array(
            'key' => 'field_5d1c0239537f7',
            'label' => 'Banner Options',
            'name' => 'location_single_banner_options',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5bee756e5cfd1',
						'operator' => '==',
						'value' => 1,
					),
				),
			),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_387e1a019f972',
                    'label' => 'Banner Display',
                    'name' => 'show_page_banner',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => 'Show',
                    'ui_off_text' => 'Hide',
                ),
                array(
                    'key' => 'field_578c36efwde51',
                    'label' => 'Banner Image',
                    'name' => 'location_single_page_banner',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                      'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_387e1a019f972',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
            ),
		),
		array(
			'key' => 'field_5c1307d7ea33d',
			'label' => 'Elements',
			'name' => 'ls_sp_elements',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5bc441288a48f' => array (
					'key' => '5bc441288a48f',
					'name' => 'related',
					'label' => 'Map / Related',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5bedfa78f183f',
							'label' => 'Related Layout',
							'name' => 'ls_sp_related_layout',
							'type' => 'clone',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array (
								0 => 'field_5c5a7900d3wdf',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc081129b90e',
							'label' => 'Header',
							'name' => 'ls_sp_related_header',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5b90d65472f05',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bc081129ba0e',
							'label' => 'Content',
							'name' => 'ls_sp_related_content',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5bc4312880187', // content to display
								1 => 'field_5c5a7940d54d3', // Text to display
								2 => 'field_5c5a7940d34d1', // max number of words
								3 => 'field_5c5a7940d43er', // max number of posts
								4 => 'field_5adec1ee78fd6', // order by
								5 => 'field_5addb2ee89ge7', // order
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array (
							'key' => 'field_5bedfa78f083e',
							'label' => 'Related Design',
							'name' => 'ls_related_design',
							'type' => 'clone',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array (
								0 => 'field_5b8e79de0c5a7',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5c13077f05123' => array(
					'key' => '5c13077f05123',
					'name' => 'global_element',
					'label' => 'Global Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c1307d8da34d',
							'label' => 'Select Element',
							'name' => 'pe_g_select',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
		),
		array (
			'key' => 'field_5bedfa77d7ef6',
			'label' => 'Map',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
            'key' => 'field_5b0b1826e619e',
            'label' => 'Map Design Code 1',
            'name' => 'map_design_code',
            'type' => 'textarea',
            'instructions' => 'The default map design code. Only accepts json code. Click <a href="https://snazzymaps.com" target="_blank">https://snazzymaps.com</a> to generate or get a map design code.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => '',
        ),
        array(
            'key' => 'field_5b0c1826e629e',
            'label' => 'Map Design Code 2',
            'name' => 'map_design_code_2',
            'type' => 'textarea',
            'instructions' => 'The map design code for Layout 2. Only accepts json code. Click <a href="https://snazzymaps.com" target="_blank">https://snazzymaps.com</a> to generate or get a map design code.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => '',
        ),
        array(
            'key' => 'field_5b0b1826e719e',
            'label' => 'Map Default Marker',
            'name' => 'map_default_marker',
            'type' => 'image',
            'instructions' => 'This will be used as the default marker image on Location Map',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5b0b1826e719f',
            'label' => 'Map Selected Marker',
            'name' => 'map_selected_marker',
            'type' => 'image',
            'instructions' => 'This will be used as the marker image on Location Map when the marker is selected',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5b0b1826e819e',
            'label' => 'Map Center Latitude',
            'name' => 'map_center_lat',
            'type' => 'text',
			'value' => NULL,
			'instructions' => 'Default: -24.766785',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '-24.766785',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
        ),
        array(
            'key' => 'field_5b0b1826e819f',
            'label' => 'Map Center Longitude',
            'name' => 'map_center_lng',
            'type' => 'text',
			'value' => NULL,
			'instructions' => 'Default: 134.824219',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '134.824219',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
        ),
        array(
            'key' => 'field_5b0b1826e8190',
            'label' => 'Map Zoom',
            'name' => 'map_zoom',
            'type' => 'text',
			'value' => NULL,
			'instructions' => 'Default: 4.7',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '4.7',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5cff079a48541',
			'label' => 'Info Windows',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'hic-header-section',
				'id' => '',
			),
			'message' => 'Fields below will override the display of contact details on map and location pages',
			'new_lines' => 'br',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5af96b68c9870',
			'label' => 'Preview Layout',
			'name' => 'info_window_layout',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'info-window-style-1' => 'Large Preview',
				'info-window-style-2' => 'Small Preview',
			),
			'allow_null' => 0,
			'default_value' => 'small-preview-layout',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5bcc4811344d3',
			'label' => 'Preview Content',
			'name' => 'preview_content_to_display',
			'type' => 'checkbox',
			'instructions' => 'Location name and address are visible by default',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(                            
				'image' => 'Featured Image/Gallery',
				'rating' => 'Rating',
				'content' => 'Content',
				'phone' => 'Phone',
				'email' => 'Email',
				'opening_hours' => 'Opening Hours',
				'social-media' => 'Social Media',
				'contact-person' => 'Contact Person',
				'website' => 'Website',
				'button'	=> 'Button',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
				0 => 'phone',
				1 => 'button',
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5bee856e5cfe3',
			'label' => 'Contact Details Label',
			'name' => 'ls_contact_details_label',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bee756e5cfd2',
			'label' => 'Phone Number Label',
			'name' => 'ls_phone_number_label',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bee756e5cfd3',
			'label' => 'Email Address Label',
			'name' => 'ls_email_address_label',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bef756e5cfd4',
			'label' => 'Opening Hours Label',
			'name' => 'ls_opening_hours_label',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bee756e5cfdf',
			'label' => 'Visit Website Label',
			'name' => 'ls_visit_website_label',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5bee756e5cfd4',
			'label' => 'Learn More Button Label',
			'name' => 'ls_learn_more_label',
			'type' => 'text',
			'value' => NULL,
			'instructions' => 'Defalt: Learn More',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_578d41fce40dc',
			'label' => 'Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bee756f5d1e1',
						'operator' => '==',
						'value' => 1,
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b001c8a6bdf6',
			'label' => 'Footer Columns',
			'name' => 'ls_footer_columns',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5b001d4a5197a',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Column',
			'sub_fields' => array(
				array(
					'key' => 'field_5b001d4a5197a',
					'label' => 'Title',
					'name' => 'ls_footer_col_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5b015163ff767',
					'label' => 'Blurb',
					'name' => 'ls_footer_col_blurb',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5b001d9a51971',
					'label' => 'Select Element',
					'name' => 'ls_footer_col_element',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Please Select' => 'Please Select',
						'logo' => 'Logo or Image',
						'primary-footer-menu' => 'Footer Menu (1st)',
						'secondary-footer-menu' => 'Footer Menu (2nd)',
						'tertiary-footer-menu' => 'Footer Menu (3rd)',
						'footer-4-menu' => 'Footer Menu (4th)',
						'social-media' => 'Social Media Links',
						'contact-information' => 'Contact Information',
						'text-editor' => 'Text Editor',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5b001c8a6bdf7',
					'label' => 'Text Editor',
					'name' => 'ls_footer_col_editor',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5b001d9a51971',
								'operator' => '==',
								'value' => 'text-editor',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_5c204dac082b4',
			'label' => 'Enable Back To Top',
			'name' => 'ls_back_to_top_enable',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5b12e76863198',
			'label' => 'Back To Top',
			'name' => 'ls_back_to_top_options',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c204dac082b4',
						'operator' => '==',
						'value' => 1,
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5b08f1ac4aa4e',
					'label' => 'Icon Type',
					'name' => 'icon_type',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'icon' => 'FA Icon',
						'image' => 'Image Icon',
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_574281edd3c03',
					'label' => 'FA Icon',
					'name' => 'icon',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5b08f1ac4aa4e',
								'operator' => '==',
								'value' => "icon",
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'fas',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 1,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_5c70dc26cf104',
					'label' => 'Image Icon',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5b08f1ac4aa4e',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5bc2a24ec833a',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bc2a24ec833b',
					'label' => 'Tool Tip',
					'name' => 'tooltip',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5b18f1ac4aa4f',
					'label' => 'Position',
					'name' => 'position',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'top-center' => 'Top Center',
						'top-right' => 'Top Right',
						'middle-right' => 'Middle Right',
						'bottom-right' => 'Bottom Right',
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
		array(
			'key' => 'field_578e989db45f7',
			'label' => 'Colophon',
			'name' => 'ls_after_footer_link',
			'type' => 'repeater',
			'instructions' => 'Links underneath Footer section	(e.g Privacy Policy , Terms and Disclaimer). Max is 4 links.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 4,
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array(
				array(
					'key' => 'field_578e9945b45f9',
					'label' => 'Link',
					'name' => 'after_footer_url',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_5bf373eb754ee',
			'label' => 'Copyright Message',
			'name' => 'ls_copyright_message',
			'type' => 'wysiwyg',
			'instructions' => 'Put code [hs_year] to get the current Year. e.g. Company [hs_year]. All rights reserved.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'text',
			'media_upload' => 0,
			'toolbar' => 'full',
			'delay' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-location-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
);

acf_add_local_field_group($settings);

endif;