<?php

if( function_exists('acf_add_local_field_group') ):

$settings = array (
	'key' => 'group_5beefa77d2978',
	'title' => 'Location Post Settings',
	'fields' => array (
        array (
			'key' => 'field_5eedfa77d8ff6',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5eed2e7201333',
			'label' => 'Slug',
			'name' => 'location_post_slug',
			'type' => 'text',
			'instructions' => 'Please make sure to save <a href=\'options-permalink.php\' target=\'_blank\'>permalink</a> settings after you update this field. Please also take note that if slug have equivalent page slug, the archive will be automatically disabled.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'location_post',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5beefa77d7bf3',
			'label' => 'Sidebar',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
            'key' => 'field_432e1239426e6',
            'label' => 'Location Post Pages',
            'name' => 'location_post_sidebar',
            'type' => 'group',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array (
                array(
                    'key' => 'field_5ec0cf7a43425',
                    'label' => 'Single Page',
                    'name' => 'post_sp_sidebar',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'none' => 'None',
                        'has-sidebar-left' => 'Left',
                        'has-sidebar-right' => 'Right',
                        'has-sidebar-both' => 'Both',
                    ),
                    'allow_null' => 0,
                    'default_value' => 'radio',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_5bc23abee233e',
                    'label' => 'Left Sidebar',
                    'name' => 'sp_left_sidebar',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_5ec0cf7a43425',
                                'operator' => '==',
                                'value' => 'has-sidebar-left',
                            ),
                        ),   
                        array (
                            array (
                                'field' => 'field_5ec0cf7a43425',
                                'operator' => '==',
                                'value' => 'has-sidebar-both',
                            ),
                        ),                       
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => 'sidebar-options',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => 0,
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5bc23abdd3140',
                    'label' => 'Right Sidebar',
                    'name' => 'sp_right_sidebar',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_5ec0cf7a43425',
                                'operator' => '==',
                                'value' => 'has-sidebar-right',
                            ),
                        ),
                        array (
                            array (
                                'field' => 'field_5ec0cf7a43425',
                                'operator' => '==',
                                'value' => 'has-sidebar-both',
                            ),
                        ),                        
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => 'sidebar-options',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => 0,
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_6dd0ef7c73436',
                    'label' => 'Archive Page',
                    'name' => 'post_ap_sidebar',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'none' => 'None',
                        'has-sidebar-left' => 'Left',
                        'has-sidebar-right' => 'Right',
                        'has-sidebar-both' => 'Both',
                    ),
                    'allow_null' => 0,
                    'default_value' => 'radio',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),  
                array(
                    'key' => 'field_5bc23abee124e',
                    'label' => 'Left Sidebar',
                    'name' => 'ap_left_sidebar',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_6dd0ef7c73436',
                                'operator' => '==',
                                'value' => 'has-sidebar-left',
                            ),
                        ),   
                        array (
                            array (
                                'field' => 'field_6dd0ef7c73436',
                                'operator' => '==',
                                'value' => 'has-sidebar-both',
                            ),
                        ),                       
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => 'sidebar-options',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => 0,
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5bc23abdd214e',
                    'label' => 'Right Sidebar',
                    'name' => 'ap_right_sidebar',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array (
                        array (
                            array (
                                'field' => 'field_6dd0ef7c73436',
                                'operator' => '==',
                                'value' => 'has-sidebar-right',
                            ),
                        ),
                        array (
                            array (
                                'field' => 'field_6dd0ef7c73436',
                                'operator' => '==',
                                'value' => 'has-sidebar-both',
                            ),
                        ),                        
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => 'sidebar-options',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'default_value' => 0,
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),     
            ),
        ),
		array (
			'key' => 'field_5beefa77d7ef5',
			'label' => 'Single Page',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
            'key' => 'field_5d1d0239537f7',
            'label' => 'Banner Options',
            'name' => 'location_post_single_banner_options',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_387f1a019f972',
                    'label' => 'Banner Display',
                    'name' => 'show_page_banner',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => 'Show',
                    'ui_off_text' => 'Hide',
                ),
                array(
                    'key' => 'field_578d36efwde51',
                    'label' => 'Banner Image',
                    'name' => 'location_post_single_page_banner',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                      'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_387f1a019f972',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5c662cc437864',
            'label' => 'Post Meta Options',
            'name' => 'single_location_post_meta_options',
            'type' => 'checkbox',
            'instructions' => 'Check post meta data to display on the page',
            'required' => 0,
           
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'date' => 'Date',
                'author' => 'Author',
            ),
            'allow_custom' => 0,
            'default_value' => array(
            ),
            'layout' => 'horizontal',
            'toggle' => 0,
            'return_format' => 'value',
            'save_custom' => 0,
        ),
		array(
			'key' => 'field_5c1407d7ea33d',
			'label' => 'Elements',
			'name' => 'lps_sp_elements',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5bc531288a48f' => array (
                    'key' => '5bc531288a48f',
                    'name' => 'related',
                    'label' => 'Related',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_5beefa77f182f',
                            'label' => 'Related Layout',
                            'name' => 'lps_sp_related_layout',
                            'type' => 'clone',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array (
                                0 => 'field_5b8e79de0c57b',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                        array(
                            'key' => 'field_5bc181119b8fe',
                            'label' => 'Header',
                            'name' => 'lps_sp_related_header',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array(
                                0 => 'group_5b90d65472f05',
                            ),
                            'display' => 'group',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                        array(
                            'key' => 'field_5bc181119b9fe',
                            'label' => 'Content Options',
                            'name' => 'lps_sp_related_content_option',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array(
                                0 => 'field_5c662cc437864',
                                1 => 'field_5adbcd69a0642',
                            ),
                            'display' => 'group',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                        array (
                            'key' => 'field_5beefa77f082e',
                            'label' => 'Related Design',
                            'name' => 'lps_related_design',
                            'type' => 'clone',
                            'value' => NULL,
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array (
                                0 => 'field_5b8e79de0c5a7',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
				'5c14077f05123' => array(
					'key' => '5c14077f05123',
					'name' => 'global_element',
					'label' => 'Global Element',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c1407d8da34d',
							'label' => 'Select Element',
							'name' => 'pe_g_select',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-location-post-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
);

acf_add_local_field_group($settings);

endif;